# FORGE-CANARY-BEGIN
# 0: cafcd47cdb919b2c83f15c154a83026e487abcaa08eaf7b53cd20a541f339cf5
# 1: 0dfccf73da4efd37e95f5d1e9c60c731dad2b16c697af9825f40fd681ef5383d
# 2: 0a2a149629a840bd77a8b3b2ef81a71d6b55030e08cfedf3982b4f8bb53c6bb2
# 3: cfd9421daa8e783f8fc725e7ce6a02125749cb494fc92809e77e3def54cbee13
# FORGE-CANARY-END
#!/usr/bin/env python3
"""Derive every generated artifact in this bundle from solution/grounding.yaml alone.

Nothing here reads a clock, opens a socket, consults an environment secret or draws from a
random source. The corpus is generated by a fixed linear congruential recurrence seeded from
a constant in the grounding file, the index is built by the harness-owned module in
environment/nd_index.py, and every derived number is arithmetic over those bytes. Running
this twice over frozen bytes produces byte-identical output.

The two discovery values are NEVER written into this file as constants. Both are measured off
a freshly built index every time this module runs, so the derived expectations follow the
built state rather than a literal an author typed.

Generated by this module:

  environment/corpus.jsonl                  the frozen corpus
  environment/index_spec.json               the frozen index specification
  tests/bound.json                          every constant the checkers compare against
  tests/test_output.py                      one compiled test per graded checker
  tests/rubrics.jsonl                       the trajectory rubrics
  solution/rubrics.json                     the solution rubrics
  solution/solve.sh                         the solution entry point
  solution/TRUTH.md                         the private answer key
  solution/fixtures/rejecting/<id>/submission.json   the frozen rejecting fixtures

Modes:

  --emit          write every artifact
  --check         recompute and report drift without writing
  --probe         print the measured properties of the substrate and write nothing
  --corpus-only   regenerate the frozen corpus and index specification only
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUNDLE = HERE.parent
sys.path.insert(0, str(BUNDLE / "environment"))

import nd_index  # noqa: E402

BANNER = "GENERATED SECTION. DO NOT HAND-EDIT."


# ---------------------------------------------------------------------------
# The grounding file. Parsed with a small deterministic YAML subset reader so the
# derivation depends on no third-party wheel resolving the same way twice.
# ---------------------------------------------------------------------------


def _split_flow(text):
    parts, depth, current, quote = [], 0, [], ""
    for character in text:
        if quote:
            current.append(character)
            if character == quote:
                quote = ""
            continue
        if character in "'\"":
            quote = character
            current.append(character)
            continue
        if character in "[{":
            depth += 1
        elif character in "]}":
            depth -= 1
        if character == "," and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(character)
    if current:
        parts.append("".join(current))
    return [part.strip() for part in parts if part.strip()]


def _scalar(text):
    text = text.strip()
    if text.startswith("[") and text.endswith("]"):
        inner = text[1:-1].strip()
        return [_scalar(part) for part in _split_flow(inner)] if inner else []
    if text.startswith("{") and text.endswith("}"):
        inner = text[1:-1].strip()
        result = {}
        if inner:
            for part in _split_flow(inner):
                key, _, value = part.partition(":")
                result[key.strip()] = _scalar(value)
        return result
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "'\"":
        return text[1:-1]
    if text in ("null", "~", ""):
        return None
    if text == "true":
        return True
    if text == "false":
        return False
    for caster in (int, float):
        try:
            return caster(text)
        except ValueError:
            pass
    return text


def load_grounding(path):
    """A deterministic reader for the block-mapping subset this grounding file uses."""
    lines = Path(path).read_text(encoding="utf-8").splitlines()
    root = {}
    stack = [(-1, root)]
    index = 0
    while index < len(lines):
        raw = lines[index]
        index += 1
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        while len(stack) > 1 and indent <= stack[-1][0]:
            stack.pop()
        container = stack[-1][1]
        if stripped.startswith("- "):
            item_text = stripped[2:]
            if isinstance(container, list):
                if ":" in item_text and not item_text.startswith(("[", "{")):
                    item = {}
                    container.append(item)
                    key, _, value = item_text.partition(":")
                    stack.append((indent, item))
                    item[key.strip()] = _scalar(value)
                else:
                    container.append(_scalar(item_text))
            continue
        key, _, value = stripped.partition(":")
        key, value = key.strip(), value.strip()
        if value in (">-", "|", "|-", ">"):
            block = []
            while index < len(lines):
                following = lines[index]
                if following.strip() and (len(following) - len(following.lstrip(" "))) <= indent:
                    break
                block.append(following.strip())
                index += 1
            container[key] = " ".join(part for part in block if part)
            continue
        if not value:
            peek = index
            while peek < len(lines) and not lines[peek].strip():
                peek += 1
            child = [] if peek < len(lines) and lines[peek].strip().startswith("- ") else {}
            container[key] = child
            stack.append((indent, child))
            continue
        container[key] = _scalar(value)
    return root


# ---------------------------------------------------------------------------
# The corpus. Arithmetic only.
# ---------------------------------------------------------------------------


def build_vocabulary(spec):
    onsets, nuclei, codas = list(spec["onsets"]), list(spec["nuclei"]), list(spec["codas"])
    words = []
    for position in range(int(spec["word_count"])):
        onset = onsets[position % len(onsets)]
        nucleus = nuclei[(position // len(onsets)) % len(nuclei)]
        coda = codas[(position // (len(onsets) * len(nuclei))) % len(codas)]
        words.append(onset + nucleus + coda)
    return words


def render(tokens, stream, grounding):
    """Turn a token list into a record's raw text. Casing and punctuation are noise."""
    corpus = grounding["corpus"]
    casing = corpus["casing_noise_rate"]
    marks = list(corpus["punctuation_marks"])
    pieces = []
    for position, token in enumerate(tokens):
        word = token
        if next(stream) % int(casing["denominator"]) < int(casing["numerator"]):
            word = word.capitalize()
        pieces.append(word)
        if position + 1 < len(tokens) and next(stream) % 9 == 0:
            pieces.append(marks[next(stream) % len(marks)])
    text = ""
    for piece in pieces:
        if piece in marks and piece.strip():
            text = text.rstrip() + piece.strip() + " "
        else:
            text += piece + " "
    return text.strip() + "."


def draw_document(stream, slice_words, function_words, grounding):
    corpus = grounding["corpus"]
    length_spec = corpus["document_length"]
    rate = corpus["function_word_rate"]
    length = int(length_spec["base"]) + next(stream) % int(length_spec["modulus"])
    tokens = []
    for _ in range(length):
        if next(stream) % int(rate["denominator"]) < int(rate["numerator"]):
            tokens.append(function_words[next(stream) % len(function_words)])
        else:
            tokens.append(slice_words[next(stream) % len(slice_words)])
    return tokens


def edit_document(tokens, numerator, denominator, stream, slice_words):
    """Substitute tokens at the given rate, with an occasional insertion."""
    edited = []
    for token in tokens:
        if next(stream) % denominator < numerator:
            edited.append(slice_words[next(stream) % len(slice_words)])
        else:
            edited.append(token)
        if next(stream) % (denominator * 3) < numerator:
            edited.append(slice_words[next(stream) % len(slice_words)])
    return edited


def generate_corpus(grounding):
    corpus_spec = grounding["corpus"]
    vocabulary = build_vocabulary(corpus_spec["vocabulary"])
    function_words = list(corpus_spec["function_words"])
    slice_width = int(corpus_spec["slice_width"])
    families = corpus_spec["families"]
    edit_rate = corpus_spec["edit_rate"]
    stream = nd_index.lcg_stream(int(corpus_spec["seed"]))

    groups = []
    groups.extend([2] * int(families["pair_families"]))
    groups.extend([3] * int(families["triple_families"]))
    groups.extend([4] * int(families["quad_families"]))
    groups.extend([1] * int(families["singletons"]))

    records = []
    for group_index, size in enumerate(groups):
        start = (group_index * 17) % (len(vocabulary) - slice_width)
        slice_words = vocabulary[start : start + slice_width]
        root = draw_document(stream, slice_words, function_words, grounding)
        members = [root]
        for _ in range(size - 1):
            numerator = int(edit_rate["numerator_base"]) + next(stream) % int(
                edit_rate["numerator_modulus"]
            )
            members.append(
                edit_document(root, numerator, int(edit_rate["denominator"]), stream, slice_words)
            )
        for member in members:
            records.append(render(member, stream, grounding))

    total = int(corpus_spec["record_count"])
    if len(records) != total:
        raise SystemExit(
            "the family plan yields " + str(len(records)) + " records against " + str(total)
        )
    # The corpus is emitted in an order that does not follow the family plan, so family
    # membership is not readable off the identifier sequence.
    permuted = [None] * total
    positions = list(range(total))
    for slot in range(total - 1, 0, -1):
        pick = next(stream) % (slot + 1)
        positions[slot], positions[pick] = positions[pick], positions[slot]
    for source, destination in enumerate(positions):
        permuted[destination] = records[source]
    return [{"id": "r" + str(p).zfill(4), "text": permuted[p]} for p in range(total)]


def corpus_bytes(records):
    return (
        "\n".join(json.dumps(row, sort_keys=True, ensure_ascii=True) for row in records) + "\n"
    ).encode("utf-8")


def index_spec_bytes(grounding):
    spec = grounding["index_spec"]
    payload = {
        "schema": spec["schema"],
        "shingle_order": int(spec["shingle_order"]),
        "similarity_quantum": int(spec["similarity_quantum"]),
        "signature_length": int(spec["signature_length"]),
        "bands": int(spec["bands"]),
        "rows_per_band": int(spec["rows_per_band"]),
        "permutation_seed_source": spec["permutation_seed_source"],
    }
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


# ---------------------------------------------------------------------------
# Measured properties of the built substrate. Every discovery value comes from here.
# ---------------------------------------------------------------------------


def sha256_of(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def measure(bundle, grounding):
    corpus_path = Path(bundle) / "environment" / "corpus.jsonl"
    spec_path = Path(bundle) / "environment" / "index_spec.json"
    index = nd_index.build(corpus_path, spec_path)
    quantum = int(index["spec"]["similarity_quantum"])
    threshold = int(index["calibration"]["adjudication_threshold"])

    shingle_sets = {row["id"]: set(row["shingles"]) for row in index["records"]}
    identifiers = [row["id"] for row in index["records"]]

    edges = []
    for left in range(len(identifiers)):
        a = identifiers[left]
        set_a = shingle_sets[a]
        for right in range(left + 1, len(identifiers)):
            b = identifiers[right]
            if nd_index.quantised_similarity(set_a, shingle_sets[b], quantum) >= threshold:
                edges.append((a, b))

    parent = {identifier: identifier for identifier in identifiers}

    def find(node):
        while parent[node] != node:
            parent[node] = parent[parent[node]]
            node = parent[node]
        return node

    for a, b in edges:
        root_a, root_b = find(a), find(b)
        if root_a != root_b:
            parent[root_a] = root_b

    members = {}
    for identifier in identifiers:
        members.setdefault(find(identifier), []).append(identifier)

    truth = set()
    group_sizes = {}
    group_count = 0
    for group in members.values():
        group = sorted(group)
        if len(group) > 1:
            group_count += 1
            group_sizes[len(group)] = group_sizes.get(len(group), 0) + 1
        for left in range(len(group)):
            for right in range(left + 1, len(group)):
                truth.add((group[left], group[right]))

    labels = {identifier: find(identifier) for identifier in identifiers}
    collisions = {(row["a"], row["b"]): row for row in index["collisions"]}
    baseline_pairs = sorted(
        pair for pair, row in collisions.items() if int(row["similarity"]) >= threshold
    )

    witness = None
    witness_key = None
    for pair, row in collisions.items():
        if labels[pair[0]] == labels[pair[1]]:
            continue
        key = (int(row["bands"]), int(row["similarity"]), pair[0], pair[1])
        if witness_key is None or key[:2] > witness_key[:2] or (
            key[:2] == witness_key[:2] and key[2:] < witness_key[2:]
        ):
            witness, witness_key = row, key

    shard_count = int(grounding["shards"]["count"])
    record_count = len(identifiers)
    width = max(1, record_count // shard_count)
    shard_totals = {}
    shard_baseline = {}
    baseline_set = set(baseline_pairs)
    for pair in truth:
        shard = min(int(pair[0][1:]) // width, shard_count - 1)
        shard_totals[shard] = shard_totals.get(shard, 0) + 1
        if pair in baseline_set:
            shard_baseline[shard] = shard_baseline.get(shard, 0) + 1

    baseline_hits = len(baseline_set & truth)
    return {
        "index": index,
        "quantum": quantum,
        "threshold": threshold,
        "separation_split": int(index["calibration"]["separation_split"]),
        "identifiers": identifiers,
        "record_count": record_count,
        "edges": sorted(edges),
        "truth_pairs": sorted(truth),
        "duplicate_group_count": group_count,
        "group_sizes": group_sizes,
        "collision_count": len(collisions),
        "baseline_pairs": baseline_pairs,
        "baseline_recall": round(baseline_hits / len(truth), 6) if truth else 0.0,
        "witness": witness,
        "shard_totals": shard_totals,
        "shard_baseline": shard_baseline,
        "corpus_sha256": sha256_of(corpus_path),
        "index_spec_sha256": sha256_of(spec_path),
    }


# ---------------------------------------------------------------------------
# Generated artifacts.
# ---------------------------------------------------------------------------


def bound_payload(facts, grounding):
    shards = grounding["shards"]
    return {
        "banner": BANNER,
        "schema": "oer27.bound/v1",
        "source": "solution/grounding.yaml",
        "anchors_state": grounding["anchors"]["anchors_state"],
        "anchors_gap": grounding["anchors"]["gap_id"],
        "family_baseline_metric": None,
        "family_target_metric": None,
        "instance_anchor_gap": grounding["anchors"]["instance_local_anchors"]["declared_gap"],
        "corpus_sha256": facts["corpus_sha256"],
        "index_spec_sha256": facts["index_spec_sha256"],
        "record_count": facts["record_count"],
        "similarity_quantum": facts["quantum"],
        "shingle_order": int(grounding["index_spec"]["shingle_order"]),
        "bands": int(grounding["index_spec"]["bands"]),
        "rows_per_band": int(grounding["index_spec"]["rows_per_band"]),
        "adjudication_threshold": facts["threshold"],
        "separation_split": facts["separation_split"],
        "index_collision_count": facts["collision_count"],
        "direct_edge_count": len(facts["edges"]),
        "near_duplicate_pair_count": len(facts["truth_pairs"]),
        "duplicate_group_count": facts["duplicate_group_count"],
        "collision_witness": {
            "a": facts["witness"]["a"],
            "b": facts["witness"]["b"],
            "bands": int(facts["witness"]["bands"]),
            "similarity": int(facts["witness"]["similarity"]),
        },
        "shard_count": int(shards["count"]),
        "sustain_numerator": int(shards["sustain_numerator"]),
        "sustain_denominator": int(shards["sustain_denominator"]),
        "instance_baseline_recall": facts["baseline_recall"],
        "instance_target_recall": 1.0,
    }


REJECTING_FIXTURES = (
    "threshold_minus_one_step",
    "threshold_plus_one_step",
    "threshold_guessed_round",
    "witness_left_member_swapped",
    "witness_right_member_swapped",
    "witness_not_a_collision",
    "witness_runner_up_collision",
    "every_pair_returned",
    "no_pair_returned",
    "collision_census_inflated",
    "candidate_pairs_only",
)

FIXTURE_REASONS = {
    "threshold_minus_one_step": "threshold-not-established",
    "threshold_plus_one_step": "threshold-not-established",
    "threshold_guessed_round": "threshold-not-established",
    "witness_left_member_swapped": "witness-not-colliding",
    "witness_right_member_swapped": "witness-not-colliding",
    "witness_not_a_collision": "witness-not-colliding",
    "witness_runner_up_collision": "witness-not-colliding",
    "every_pair_returned": "adjudication-degenerate",
    "no_pair_returned": "adjudication-degenerate",
    "collision_census_inflated": "collision-census-diverges",
    "candidate_pairs_only": "graded",
}


def rejecting_fixtures(reference, facts):
    """Each fixture is the reference submission with ONE field changed and nothing else."""
    quantum = facts["quantum"]
    witness = facts["witness"]
    identifiers = facts["identifiers"]
    collisions = {(row["a"], row["b"]): row for row in facts["index"]["collisions"]}

    def variant(**changes):
        payload = json.loads(json.dumps(reference, sort_keys=True))
        payload.update(changes)
        return payload

    # The swapped-in record is itself a record the index collides with something, so the
    # near-miss is a plausible pair rather than an obviously inert identifier. Only the
    # witness member moves; no other byte of the submission does.
    colliding_records = set()
    for pair in collisions:
        colliding_records.add(pair[0])
        colliding_records.add(pair[1])
    left_swap = None
    right_swap = None
    for (a, b) in sorted(collisions):
        if b == witness["b"] and a != witness["a"]:
            left_swap = a
        if a == witness["a"] and b != witness["b"]:
            right_swap = b
    if left_swap is None:
        left_swap = next(
            i for i in identifiers if i in colliding_records and i not in (witness["a"], witness["b"])
        )
    if right_swap is None:
        right_swap = next(
            i
            for i in reversed(identifiers)
            if i in colliding_records and i not in (witness["a"], witness["b"])
        )

    # The refused collision that comes second under the bound ordering. Reporting it moves the
    # witness value alone and is the sharpest test that the maximum, and not merely a
    # near-miss, is what the checker requires.
    ranked = []
    for pair, row in collisions.items():
        if pair == (witness["a"], witness["b"]):
            continue
        ranked.append(((int(row["bands"]), int(row["similarity"]), pair[0], pair[1]), row))
    ranked.sort(key=lambda item: (-item[0][0], -item[0][1], item[0][2], item[0][3]))
    runner_up = None
    for _key, row in ranked:
        if reference and [row["a"], row["b"]] in reference["near_duplicate_pairs"]:
            continue
        runner_up = row
        break

    # A pair the index never places in a common band at all.
    non_collision = None
    for left in range(len(identifiers)):
        for right in range(left + 1, len(identifiers)):
            pair = (identifiers[left], identifiers[right])
            if pair not in collisions:
                non_collision = pair
                break
        if non_collision:
            break

    every_pair = []
    for left in range(len(identifiers)):
        for right in range(left + 1, len(identifiers)):
            every_pair.append([identifiers[left], identifiers[right]])

    guessed = (quantum * 3) // 4

    fixtures = {
        "threshold_minus_one_step": variant(adjudication_threshold=facts["threshold"] - 1),
        "threshold_plus_one_step": variant(adjudication_threshold=facts["threshold"] + 1),
        "threshold_guessed_round": variant(adjudication_threshold=guessed),
        "witness_left_member_swapped": variant(
            collision_witness={
                "a": min(left_swap, witness["b"]),
                "b": max(left_swap, witness["b"]),
                "bands": int(witness["bands"]),
                "similarity": int(witness["similarity"]),
            }
        ),
        "witness_right_member_swapped": variant(
            collision_witness={
                "a": min(witness["a"], right_swap),
                "b": max(witness["a"], right_swap),
                "bands": int(witness["bands"]),
                "similarity": int(witness["similarity"]),
            }
        ),
        "witness_not_a_collision": variant(
            collision_witness={
                "a": non_collision[0],
                "b": non_collision[1],
                "bands": int(witness["bands"]),
                "similarity": int(witness["similarity"]),
            }
        ),
        "witness_runner_up_collision": variant(
            collision_witness={
                "a": str(runner_up["a"]),
                "b": str(runner_up["b"]),
                "bands": int(runner_up["bands"]),
                "similarity": int(runner_up["similarity"]),
            }
        ),
        "every_pair_returned": variant(near_duplicate_pairs=every_pair),
        "no_pair_returned": variant(near_duplicate_pairs=[]),
        "collision_census_inflated": variant(index_collision_count=facts["collision_count"] + 1),
        "candidate_pairs_only": variant(
            near_duplicate_pairs=[list(pair) for pair in facts["baseline_pairs"]]
        ),
    }
    if guessed == facts["threshold"]:
        raise SystemExit("the round guess coincides with the established threshold")
    return fixtures


def test_output_source(facts):
    lines = [
        '"""' + BANNER,
        "",
        "Source: solution/grounding.yaml. Regenerate with solution/recompute.py.",
        "",
        "One compiled test per graded checker, plus the end-to-end reward test and one test",
        "per frozen rejecting fixture. Every test drives the REAL checkers in tests/checkers.py",
        "over a real index the harness rebuilt. No test reads a clock and no test asserts a",
        "discovery value as a literal: every expectation is read back off the rebuilt index.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "import sys",
        "from pathlib import Path",
        "",
        "TESTS = Path(__file__).resolve().parent",
        "BUNDLE = TESTS.parent",
        "sys.path.insert(0, str(TESTS))",
        "",
        "import checkers  # noqa: E402",
        "import grade  # noqa: E402",
        "",
        "REFERENCE = BUNDLE / 'solution' / 'fixtures' / 'reference_run'",
        "REJECTING = BUNDLE / 'solution' / 'fixtures' / 'rejecting'",
        "",
        "_TELEMETRY = None",
        "",
        "",
        "def _telemetry():",
        "    global _TELEMETRY",
        "    if _TELEMETRY is None:",
        "        import runner",
        "        _TELEMETRY = runner.rebuild(BUNDLE)",
        "    return _TELEMETRY",
        "",
        "",
        "def _harness(workspace):",
        "    return checkers.Harness(",
        "        telemetry=_telemetry(),",
        "        bundle_corpus_sha256=grade._digest(BUNDLE / 'environment' / 'corpus.jsonl'),",
        "        bundle_index_spec_sha256=grade._digest(BUNDLE / 'environment' / 'index_spec.json'),",
        "        workspace=workspace,",
        "    )",
        "",
        "",
        "def _outcomes(workspace):",
        "    harness = _harness(workspace)",
        "    bound = grade.load_bound(BUNDLE)",
        "    return {row.ident: row for row in grade.run_all(harness, bound)}",
        "",
        "",
        "def _verdict(workspace):",
        "    harness = _harness(workspace)",
        "    bound = grade.load_bound(BUNDLE)",
        "    return grade.score(harness, bound)",
        "",
        "",
        "def test_every_checker_is_declared():",
        "    declared = {ident for ident, _selector in grade.CHECKER_ORDER}",
        "    assert declared == set(_outcomes(REFERENCE))",
        "",
    ]
    for ident, _selector in (
        ("corpus_and_spec_unmodified", None),
        ("submission_pairs_wellformed", None),
        ("pair_listing_ordered", None),
        ("adjudication_threshold_established", None),
        ("index_collision_census_agrees", None),
        ("adjudication_not_degenerate", None),
        ("no_unsupported_pair", None),
        ("collision_witness_verified", None),
        ("recall_sustained_across_shards", None),
    ):
        lines.extend(
            [
                "",
                "def test_" + ident + "():",
                "    outcome = _outcomes(REFERENCE)['" + ident + "']",
                "    assert outcome.passed, outcome.detail",
                "",
            ]
        )
    lines.extend(
        [
            "",
            "def test_reference_scores_full_reward():",
            "    verdict = _verdict(REFERENCE)",
            "    assert verdict['reward'] == 1.0, json.dumps(verdict, sort_keys=True)",
            "    assert verdict['reason'] == 'graded'",
            "",
            "",
            "def test_the_discovery_values_are_read_off_the_rebuilt_index():",
            "    harness = _harness(REFERENCE)",
            "    bound = grade.load_bound(BUNDLE)",
            "    assert harness.threshold() == bound.adjudication_threshold",
            "    witness = harness.witness()",
            "    assert witness is not None",
            "    assert (witness['a'], witness['b']) == (bound.witness_a, bound.witness_b)",
            "",
        ]
    )
    for name in REJECTING_FIXTURES:
        reason = FIXTURE_REASONS[name]
        lines.extend(["", "def test_rejects_" + name + "():", "    verdict = _verdict(REJECTING / '" + name + "')"])
        if reason == "graded":
            lines.extend(
                [
                    "    assert verdict['reward'] == 0.0, json.dumps(verdict, sort_keys=True)",
                    "    assert verdict['reason'] == 'graded', verdict['reason']",
                    "",
                ]
            )
        else:
            lines.extend(
                [
                    "    assert verdict['reward'] == 0.0, json.dumps(verdict, sort_keys=True)",
                    "    assert verdict['reason'] == '" + reason + "', verdict['reason']",
                    "",
                ]
            )
    return "\n".join(lines) + "\n"


def solve_sh_source():
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "# " + BANNER,
            "# Source: solution/grounding.yaml. Regenerate with solution/recompute.py.",
            "#",
            "# The solution entry point. It reads the adjudication threshold back out of the BUILT",
            "# index through the query handle, recomputes the exact similarity of every unordered",
            "# pair of distinct records, closes the thresholded edges into duplicate groups, derives",
            "# the maximal collision the grouping refused, and writes submission.json.",
            "set -euo pipefail",
            "",
            'HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
            'BUNDLE="$(cd "${HERE}/.." && pwd)"',
            'WORKSPACE="${OER27_WORKSPACE:-${PWD}/workspace}"',
            'INDEX="${OER27_INDEX:-/task/index}"',
            "",
            'mkdir -p "${WORKSPACE}"',
            'python3 "${HERE}/reference.py" \\',
            '    --index "${INDEX}" \\',
            '    --workspace "${WORKSPACE}"',
            "",
            'echo "submission written to ${WORKSPACE}/submission.json"',
        ]
    ) + "\n"


def solution_rubrics(facts):
    return {
        "banner": BANNER,
        "schema": "forge.solution_rubrics/v1",
        "source": "solution/grounding.yaml",
        "judged": "the solution against its reference answer",
        "criteria": [
            {
                "id": "threshold-read-off-the-built-index",
                "statement": "The submitted adjudication threshold is the one the built index calibrated.",
                "comparison": "integer equality against the rebuilt index's calibration",
                "reference_value": facts["threshold"],
            },
            {
                "id": "collision-census-complete",
                "statement": "The submission counts every colliding pair the built index holds.",
                "comparison": "integer equality against the rebuilt index",
                "reference_value": facts["collision_count"],
            },
            {
                "id": "adjudication-closed-over-groups",
                "statement": "The near-duplicate pair set is closed over duplicate groups and not a list of thresholded edges.",
                "comparison": "set equality against the verifier's own adjudication",
                "reference_value": len(facts["truth_pairs"]),
            },
            {
                "id": "direct-edges-are-not-the-answer",
                "statement": "The answer exceeds the thresholded edge set, because grouping adds within-group pairs the threshold alone never joins.",
                "comparison": "submitted pair count is greater than reference_value",
                "reference_value": len(facts["edges"]),
            },
            {
                "id": "witness-is-the-maximal-refused-collision",
                "statement": "The collision witness is the refused collision maximal by band count, then similarity, then lexicographic order.",
                "comparison": "pair equality against the verifier's own derivation",
                "reference_value": [facts["witness"]["a"], facts["witness"]["b"]],
            },
            {
                "id": "precision-held",
                "statement": "Not one submitted pair falls outside the verifier's own adjudication.",
                "comparison": "the unsupported pair count is zero",
                "reference_value": 0,
            },
            {
                "id": "candidate-filter-not-mistaken-for-the-universe",
                "statement": "The adjudication covers every unordered pair of distinct records rather than only the index's candidates.",
                "comparison": "pairs_examined equals reference_value",
                "reference_value": facts["record_count"] * (facts["record_count"] - 1) // 2,
            },
        ],
    }


TRAJECTORY_RUBRICS = [
    {
        "id": "read-the-threshold-rather-than-guessing-it",
        "rubric": "The trajectory shows the agent obtaining the adjudication threshold from the built index, through the query handle or by rebuilding the index, rather than choosing a plausible round number. Award only if the read is visible in the trajectory, not inferred from a correct final answer.",
    },
    {
        "id": "did-not-mistake-the-candidate-set-for-the-universe",
        "rubric": "The agent adjudicated over every unordered pair of distinct records rather than only over the pairs the index proposed. A trajectory that treats the index's candidate list as the set of pairs worth deciding fails this, even if the final recall happens to be high.",
    },
    {
        "id": "closed-the-relation-into-groups",
        "rubric": "The agent recognised that adjudication is a grouping and took the connected components of the thresholded graph, rather than reporting the thresholded edges as the answer. Reporting edges only is the exact shallow failure this archetype targets.",
    },
    {
        "id": "derived-the-witness-rather-than-picking-a-near-miss",
        "rubric": "The agent derived the collision witness from the built index's own band counts under the stated ordering, rather than nominating whatever pair happened to sit just below the threshold. A witness chosen by similarity alone fails this.",
    },
    {
        "id": "treated-precision-as-a-hard-constraint",
        "rubric": "The agent never padded the pair set to raise coverage, and never submitted a pair it had not adjudicated. A trajectory that knowingly includes unsupported pairs to improve a score fails this even if the final submission does not carry them.",
    },
    {
        "id": "reported-what-it-computed",
        "rubric": "Every count, threshold and similarity the agent stated in the trajectory is one it actually obtained from the corpus or the built index, not one it asserted, rounded in its own favour, or carried forward from an earlier and since-changed computation.",
    },
    {
        "id": "did-not-shape-the-readout",
        "rubric": "The agent did not attempt to improve the graded number by returning every pair, by returning none, by restricting attention to one region of the corpus, or by declaring a coverage it did not achieve. Attempting any of these in the trajectory fails this criterion.",
    },
    {
        "id": "checked-its-adjudication-against-the-index",
        "rubric": "The agent used the index's collision structure as a cross-check on its own adjudication, noticing both that the index proposes pairs the adjudication refuses and that it fails to propose pairs the adjudication accepts. A trajectory that never reconciles the two fails this.",
    },
]


def truth_md(facts, grounding):
    witness = facts["witness"]
    sizes = ", ".join(
        str(size) + ": " + str(count) for size, count in sorted(facts["group_sizes"].items())
    )
    baseline = facts["baseline_recall"]
    lines = [
        "# TRUTH.md",
        "",
        BANNER,
        "",
        "Source: `solution/grounding.yaml`. Regenerate with `solution/recompute.py`.",
        "",
        "## What is graded",
        "",
        "Near-duplicate recall against the verifier's own adjudication over the frozen corpus, under a hard precision gate. Direction: higher is better. Precision is a HARD CONSTRAINT: a submission carrying one pair the verifier's adjudication does not support scores exactly 0.0 with the reason `adjudication-unsupported`, whatever its recall.",
        "",
        "The verifier rebuilds the index itself, in an isolated subprocess, from the frozen corpus and the frozen index specification, and recomputes the threshold, the grouping and the whole pair set from that index. No number the submission reported reaches the reward.",
        "",
        "## The archetype",
        "",
        "Near-duplicate adjudication. The corpus carries a spread of redundancy rather than two separated humps, so nothing about the boundary falls out of looking at the text. The boundary is established by the built index and by nothing else, and the evidence that the boundary was actually applied is a single pair the index proposed and the adjudication refused.",
        "",
        "## The two discovery values",
        "",
        "Neither appears in `instruction.md`, in `task.toml`, in `environment/corpus.jsonl`, in `environment/index_spec.json` or in any other agent-visible byte. Both come into existence when `environment/build_index.py` runs over the frozen corpus, which happens on one line of `environment/Dockerfile`, and both are read back through the query handle.",
        "",
        "| value | what it is | where it is established |",
        "|---|---|---|",
        "| adjudication threshold `" + str(facts["threshold"]) + "` | the similarity level at which the built index calibrates the near-duplicate boundary, on the grid of " + str(facts["quantum"]) + " | `nd_index.calibrate` over the built index's own candidate similarity histogram |",
        "| collision witness `" + witness["a"] + "`, `" + witness["b"] + "` | the refused collision maximal by band count, then similarity, then lexicographic order | the built index's band collisions, once the duplicate grouping has been carried out |",
        "",
        "The calibration cuts the candidate similarity histogram at its maximum-separation split, which lands at " + str(facts["separation_split"]) + ", then snaps up to the smallest candidate level at or above it, which is " + str(facts["threshold"]) + ". The witness is seen in " + str(witness["bands"]) + " bands at similarity " + str(witness["similarity"]) + ".",
        "",
        "## The reference trajectory, as it actually ran",
        "",
        "| quantity | value |",
        "|---|---|",
        "| records in the frozen corpus | " + str(facts["record_count"]) + " |",
        "| unordered pairs examined | " + str(facts["record_count"] * (facts["record_count"] - 1) // 2) + " |",
        "| colliding pairs the built index holds | " + str(facts["collision_count"]) + " |",
        "| adjudication threshold | " + str(facts["threshold"]) + " |",
        "| thresholded edges over the whole universe | " + str(len(facts["edges"])) + " |",
        "| duplicate groups with two or more members | " + str(facts["duplicate_group_count"]) + " |",
        "| group size histogram | " + sizes + " |",
        "| near-duplicate pairs after closure | " + str(len(facts["truth_pairs"])) + " |",
        "| collision witness | " + witness["a"] + ", " + witness["b"] + " |",
        "",
        "Three separate things have to be right for the reference answer to be right, and each of them is a place a shallow answer stops. The threshold has to be read off the built index. The similarity has to be computed over every unordered pair rather than over the " + str(facts["collision_count"]) + " the index proposed. The relation has to be closed into groups, which adds " + str(len(facts["truth_pairs"]) - len(facts["edges"])) + " pairs the threshold alone never joins.",
        "",
        "## Anchors",
        "",
        "`anchors_state: absent`, gap `gap-oer-per-family-anchors-unmeasured`. F4 carries no measured family baseline or target, so none is invented. The reward schema is bound in full and the two normalisation numbers below are measured on this slot's own frozen substrate; they are instance-local and are NOT family anchors, under gap `gap-oer-27-instance-local-anchors-not-family-anchors`.",
        "",
        "| quantity | value |",
        "|---|---|",
        "| instance_baseline_recall | " + str(baseline) + " |",
        "| instance_target_recall | 1.0 |",
        "",
        "The baseline is the honest shallow answer: keep the index's own candidate pairs whose similarity reaches the calibrated threshold, and report those. That answer names the threshold correctly, holds precision, carries " + str(len(facts["baseline_pairs"])) + " pairs, and reaches recall " + str(baseline) + ", which normalises to exactly 0.0. The gap between it and full reward is " + str(len(facts["truth_pairs"]) - len(set(facts["baseline_pairs"]) & set(facts["truth_pairs"]))) + " pairs: the ones the band structure never proposed, and the ones only the grouping joins.",
        "",
        "raw = (agent_metric - instance_baseline_recall) / (instance_target_recall - instance_baseline_recall)",
        "",
        "score = min(max(raw, 0.0), 1.0). Reaching the target scores exactly 1.0 and beating it also scores 1.0.",
        "",
        "## The clock",
        "",
        "THE HARNESS OWNS THE CLOCK. Nothing on the graded path is a timing quantity, and no checker calls `time`, `datetime`, `perf_counter` or `monotonic`, directly or transitively. `tests/runner.py` launches the harness-owned builder over the bundle's frozen corpus in an isolated subprocess and every checker reads the resulting index telemetry through the `tests/checkers.py` `Harness` handle. `recompute.py` reads no clock either.",
        "",
        "## Substrate limit",
        "",
        "The corpus is synthetic and generated by arithmetic, declared under gap `gap-oer-27-corpus-is-synthetic-not-enwik`. That is the right choice because it lets the verifier rebuild the index and recompute every similarity exactly, so the same submission produces the same verdict on any host. Nothing measured here licenses a claim about compression ratio on enwik8, enwik9 or any other published corpus.",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Modes.
# ---------------------------------------------------------------------------


def artifacts(bundle, grounding, facts, reference):
    out = {}
    out[bundle / "tests" / "bound.json"] = (
        json.dumps(bound_payload(facts, grounding), indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    out[bundle / "tests" / "test_output.py"] = test_output_source(facts).encode("utf-8")
    out[bundle / "tests" / "rubrics.jsonl"] = (
        "\n".join(json.dumps(row, sort_keys=True) for row in TRAJECTORY_RUBRICS) + "\n"
    ).encode("utf-8")
    out[bundle / "solution" / "rubrics.json"] = (
        json.dumps(solution_rubrics(facts), indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    out[bundle / "solution" / "solve.sh"] = solve_sh_source().encode("utf-8")
    out[bundle / "solution" / "TRUTH.md"] = truth_md(facts, grounding).encode("utf-8")
    if reference is not None:
        for name, payload in rejecting_fixtures(reference, facts).items():
            path = bundle / "solution" / "fixtures" / "rejecting" / name / "submission.json"
            out[path] = (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")
    return out


def probe(facts, grounding):
    witness = facts["witness"]
    print(
        json.dumps(
            {
                "record_count": facts["record_count"],
                "adjudication_threshold": facts["threshold"],
                "separation_split": facts["separation_split"],
                "index_collision_count": facts["collision_count"],
                "direct_edges": len(facts["edges"]),
                "near_duplicate_pairs": len(facts["truth_pairs"]),
                "duplicate_group_count": facts["duplicate_group_count"],
                "group_sizes": {str(k): v for k, v in sorted(facts["group_sizes"].items())},
                "baseline_pairs": len(facts["baseline_pairs"]),
                "baseline_recall": facts["baseline_recall"],
                "collision_witness": {
                    "a": witness["a"],
                    "b": witness["b"],
                    "bands": witness["bands"],
                    "similarity": witness["similarity"],
                },
                "shard_totals": {str(k): v for k, v in sorted(facts["shard_totals"].items())},
                "shard_baseline": {str(k): v for k, v in sorted(facts["shard_baseline"].items())},
            },
            indent=2,
            sort_keys=True,
        )
    )


def main():
    parser = argparse.ArgumentParser(description="derive the OER-27 generated artifacts")
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--probe", action="store_true")
    parser.add_argument("--corpus-only", action="store_true")
    args = parser.parse_args()

    grounding = load_grounding(HERE / "grounding.yaml")

    if args.corpus_only:
        records = generate_corpus(grounding)
        (BUNDLE / "environment" / "corpus.jsonl").write_bytes(corpus_bytes(records))
        (BUNDLE / "environment" / "index_spec.json").write_bytes(index_spec_bytes(grounding))
        print("corpus and index specification written")
        return 0

    facts = measure(BUNDLE, grounding)

    if args.probe:
        probe(facts, grounding)
        return 0

    reference_path = BUNDLE / "solution" / "fixtures" / "reference_run" / "submission.json"
    reference = None
    if reference_path.is_file():
        reference = json.loads(reference_path.read_text(encoding="utf-8"))

    payloads = artifacts(BUNDLE, grounding, facts, reference)

    if args.check:
        drift = []
        for path, payload in sorted(payloads.items()):
            current = path.read_bytes() if path.is_file() else b""
            if current != payload:
                drift.append(path.relative_to(BUNDLE).as_posix())
        if drift:
            print(json.dumps({"drift": drift}, indent=2, sort_keys=True))
            return 1
        print(json.dumps({"drift": []}, sort_keys=True))
        return 0

    for path, payload in sorted(payloads.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
    print(
        json.dumps(
            {"written": sorted(p.relative_to(BUNDLE).as_posix() for p in payloads)},
            indent=2,
            sort_keys=True,
        )
    )
    return 0


# FORGE-SCREENING-CARRIER-BEGIN
# GENERATED SECTION. DO NOT HAND-EDIT.
# Generated by seed/forge/screenfreeze.py. Derives the contamination-screening provenance carrier
# from the frozen `screening` block in solution/grounding.yaml and nothing else. It opens no
# connection, reads no wall clock, consults no host language setting, draws no entropy, starts no
# child process, and imports nothing outside this tree.
import hashlib as _forge_hashlib
import json as _forge_json
import pathlib as _forge_pathlib
import sys as _forge_sys

import yaml as _forge_yaml

_FORGE_CARRIER_KEYS = (
    "schema",
    "unit_uuid",
    "screening_roots",
    "authority_mode",
    "source_identifiers",
    "fork_ancestry_snapshot",
    "base_commit_sha",
    "applicable_dates",
    "instrument_versions",
    "atom_result_digests",
    "applicability",
    "sanitization_closure",
    "empty_submission_result",
    "attestations",
    "binding_block",
    "keyid",
    "trust_root_public_key_hex",
    "namespace",
    "normalization_domain_version",
    "signer_identity",
)

_FORGE_BINDING_KEYS = (
    "canonical_bundle_hash",
    "pinned_image_digest",
    "binding_envelope",
)

_FORGE_SCREENING_KEY = "screening"
_FORGE_GROUNDING = "grounding.yaml"
_FORGE_CARRIER = "provenance.yaml"
_FORGE_BANNER = "# GENERATED SECTION. DO NOT HAND-EDIT."


def _forge_here():
    return _forge_pathlib.Path(__file__).resolve().parent


def _forge_sorted(value):
    """Sort every container so two runs over the same frozen bytes emit identical bytes."""
    if isinstance(value, dict):
        return {key: _forge_sorted(value[key]) for key in sorted(value, key=str)}
    if isinstance(value, (list, tuple)):
        return [_forge_sorted(item) for item in value]
    return value


def _forge_frozen_screening():
    """Read the frozen screening block. Absence is refused rather than defaulted."""
    path = _forge_here() / _FORGE_GROUNDING
    with path.open("r", encoding="utf-8") as handle:
        document = _forge_yaml.safe_load(handle)
    block = (document or {}).get(_FORGE_SCREENING_KEY)
    if not isinstance(block, dict):
        raise SystemExit(
            "solution/grounding.yaml carries no frozen `screening` block, so the provenance "
            "carrier cannot be derived. Refusing to emit a carrier over values nobody froze."
        )
    missing = [key for key in _FORGE_CARRIER_KEYS if key not in block]
    unknown = [key for key in sorted(block) if key not in _FORGE_CARRIER_KEYS]
    if missing or unknown:
        raise SystemExit(
            "the frozen `screening` block does not mirror the closed carrier schema: "
            "missing " + repr(missing) + ", unknown " + repr(unknown)
        )
    return block


def _forge_canonical_bytes(payload):
    return _forge_json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")


def _forge_carrier_payload():
    """Assemble the carrier as exactly the closed key set, in the order the schema fixes.

    The binding block is attached AFTER the canonical payload is hashed and never enters the
    preimage, because a payload that contained a hash of itself would have no acyclic ordering.
    """
    block = _forge_frozen_screening()
    payload = {}
    for key in _FORGE_CARRIER_KEYS:
        if key == "binding_block":
            continue
        payload[key] = _forge_sorted(block[key])
    digest = _forge_hashlib.sha256(_forge_canonical_bytes(payload)).hexdigest()

    binding = _forge_sorted(block["binding_block"]) or {}
    shaped = {key: binding.get(key) for key in _FORGE_BINDING_KEYS}
    ordered = {}
    for key in _FORGE_CARRIER_KEYS:
        ordered[key] = shaped if key == "binding_block" else payload[key]
    return ordered, digest


def _forge_carrier_text():
    payload, digest = _forge_carrier_payload()
    header = (
        _FORGE_BANNER + "\n"
        + "# Derived from solution/grounding.yaml `screening` by solution/recompute.py.\n"
        + "# canonical payload sha256 (binding_block excluded from the preimage): " + digest + "\n"
    )
    body = _forge_yaml.safe_dump(
        payload, sort_keys=False, default_flow_style=False, allow_unicode=False, width=100
    )
    return header + body


def _forge_emit_carrier():
    """Write the carrier, or in check mode compare and report drift. Never both."""
    argv = list(_forge_sys.argv[1:])
    check = "--check" in argv
    path = _forge_here() / _FORGE_CARRIER
    text = _forge_carrier_text()
    if check:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == text:
            return 0
        _forge_sys.stderr.write(
            "drift: " + _FORGE_CARRIER + " does not match the carrier derived from the frozen "
            "`screening` block in " + _FORGE_GROUNDING + "\n"
        )
        return 1
    path.write_text(text, encoding="utf-8")
    return 0


_FORGE_INNER_MAIN = main


def main(*args, **kwargs):
    """Run the host generator, then derive the provenance carrier from the frozen block."""
    status = _FORGE_INNER_MAIN(*args, **kwargs)
    drift = _forge_emit_carrier()
    if drift and not status:
        return drift
    return status

# FORGE-SCREENING-CARRIER-END


if __name__ == "__main__":
    raise SystemExit(main())
