# FORGE-CANARY-BEGIN
# 0: 0ce6e02dab8686319a49ac3d4060bec5c090aff418b9ee96155aaf6a642d76d6
# 1: 177bd3d61ed18e5f97827159e42ab79dfd6f425af13b6b7ec6a6a0f8dbb64731
# 2: 657cd3d45224bda2cf5a2e2fdbd5dd7595a90ef42a0b5a7ff54791a3d942bbf8
# 3: d440daeb8f86eb6909c3618aaf12b0167d7c5f4e6965b8e1e4a568b3974348b1
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
