# FORGE-CANARY-BEGIN
# 0: 0795102fc12bf4719a1447ee1258dce6b40c5de146b7f392277cab7f71ce5e8b
# 1: 982f742bc5e5cc8d56373dc007a73a4e3cef859704d978a0284942073853e179
# 2: 6e5dac3ca7dda945a13f3a58710d16e9d07e205a92caaaf25bfe4d7d0b5ce5b9
# 3: 982ec7a3ea5444883ae6f32d974b5caeafdc6e2298e252cc4a858ae42cf7931d
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
