# FORGE-CANARY-BEGIN
# 0: ecb60d97147dbfdc981d7209b017240fff68c8a2a1b6405fc28e71e3f6bb4085
# 1: fe3ffde1a4fd6837b07490cd927e5f2f3febaf85e29d344fda7abb8ee6cea499
# 2: 300755b86316cb310322bb8b70dd1faba823a95037d6ba114012c4a76df7bf91
# 3: 43b3586d99aad44e6c8ead63b6aa5622e65897a60010d020ed05d66d543c2d82
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
