# FORGE-CANARY-BEGIN
# 0: fa130b23c0eec796b9a497cd36cc4aee90e4d7648dffad8f7fd8a367db43736b
# 1: ee00f17646056f41fc9a002ae8d8b1a4f3044866f1868786265b1e40f1683459
# 2: 920460b6e6d7772bb204d81286467f533d40b647ac1225737342296140a9b52d
# 3: d532f55278c036b9543bf04a16ea1887c523e040b4be8d605a12af7d1496da06
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
