# FORGE-CANARY-BEGIN
# 0: 6dd8d43f31bac27b14d2406d5e0c7cc9c21c8c83522f3af9bd1de5112a3e15b7
# 1: b6a2311a0de9334e4ce394ef69aa27a8dc6181cd6e71ec7098b7e46d6a286154
# 2: 68e236ed1b0edb69aca23f2a9e14fd03309eea7a9dcf640a066b5f4dc5ac49ac
# 3: 0caf423eb2477128f5fd23037572c84230c68cf28719162dacf337831fee893f
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
