#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Generated by solution/recompute.py from solution/grounding.yaml.
#
# Executable oracle for the BIA-GSN-1 kernel throughput task. It installs the private
# reference solution as the submission and runs the real verifier path.
#
# Default mode runs the graded profile on one H100.
# BIA_SMOKE=1 runs the identical code path at tiny scale on CPU with no CUDA context,
# which exists so the reference can be proven to execute end to end without an
# accelerator. In smoke mode the correctness gate and the divergence path are fully
# exercised and the timing number produced is not a claim about the operating point.
set -euo pipefail

SOLUTION_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE="$(cd "$SOLUTION_DIR/.." && pwd)"

if [ "${1:-}" = "--controls" ]; then
  exec python3 "$SOLUTION_DIR/control_runner.py" --bundle "$BUNDLE"
fi

SMOKE="${BIA_SMOKE:-0}"
if [ "$SMOKE" = "1" ]; then
  WORK="$(mktemp -d -t bia-s05-smoke-XXXXXX)"
  LOGS="$WORK/logs"
  export CUDA_VISIBLE_DEVICES=""
else
  WORK="${BIA_WORK:-/workspace}"
  LOGS="${BIA_LOGS:-/logs/verifier}"
fi

mkdir -p "$WORK/submission" "$WORK/artifacts" "$LOGS"
cp "$SOLUTION_DIR/fast_impl.py" "$WORK/submission/impl.py"

export BIA_SMOKE="$SMOKE"
export BIA_BUNDLE="$BUNDLE"
export BIA_TESTS="${BIA_TESTS:-$BUNDLE/tests}"
export BIA_ENV_DIR="${BIA_ENV_DIR:-$BUNDLE/environment}"
export BIA_SUBMISSION="$WORK/submission/impl.py"
export BIA_ARTIFACTS="$WORK/artifacts"
export BIA_LOGS="$LOGS"
export SCORE_PATH="${SCORE_PATH:-$LOGS/score.json}"
export BIA_REPORT="${BIA_REPORT:-$LOGS/report.json}"
export BIA_OUTCOMES="${BIA_OUTCOMES:-$LOGS/outcomes.json}"
export BIA_EVENTS="${BIA_EVENTS:-$LOGS/harness_events.jsonl}"
export BIA_TIMING_SUMMARY="${BIA_TIMING_SUMMARY:-$LOGS/timing_summary.json}"

bash "$BIA_TESTS/test.sh"
RC=$?
echo "score file: $SCORE_PATH"
cat "$SCORE_PATH"
echo
exit $RC
