# FORGE-CANARY-BEGIN
# 0: cb4920854945314d11473d4cbf8442538256d24e3caf8d62f59994afcf1f0fd1
# 1: 48649d76cf89f0d90bbe6729de604f0a8faf0682d9b2181279c79f6a1d86eece
# 2: 7ec076a06966d0efe00b58be2b5be98aee189e902676de07c886810dc7d402fb
# 3: 6c9ff6083570707348114f7bd994eca4011b889d3870265f4f797ae9d24f8810
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
