#!/usr/bin/env python3
"""Derives every generated artifact in this bundle from solution/grounding.yaml.

Generated here, and nowhere else:
  tests/checkers.yaml
  tests/rubrics.jsonl
  tests/test_output.py
  solution/rubrics.json
  solution/TRUTH.md

Run with --check to prove the committed bytes equal the regenerated bytes. The
generator reads only grounding.yaml and this file, so two runs on two different
hosts produce the same bytes.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BANNER = "GENERATED SECTION. DO NOT HAND-EDIT."
SOURCE_NOTE = "Source: solution/grounding.yaml. Regenerate with solution/recompute.py."
KINDS = ["VALUE", "EFFECT", "ABSENCE", "INVARIANT", "ORDERING", "DIVERGENCE"]
AGGREGATION_MODES = ["weighted_mean", "all_pass", "any_pass", "threshold", "required_pass"]
REASON_CODE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def load_grounding():
    with open(os.path.join(HERE, "grounding.yaml"), "rb") as handle:
        return yaml.safe_load(handle.read().decode("utf-8"))


def one_line(text):
    return " ".join(str(text).split())


def gen_checkers_yaml(g):
    grading = g["grading"]
    mode = grading["aggregation_mode"]
    if mode not in AGGREGATION_MODES:
        raise SystemExit("aggregation mode " + repr(mode) + " is outside the closed set")
    lines = [
        "# " + BANNER,
        "# " + SOURCE_NOTE,
        "#",
        "# Every checker below reduces to exactly one of the six kinds, names the",
        "# live-state read it traces to, names the reachable carrier that implements",
        "# it, and names the reason code that carrier emits when it scores zero.",
        "# A checker reducing to none, or to two, is invalid.",
        "schema: forge.checkers/v1",
        "schema_version: 1",
        "kinds: " + json.dumps(KINDS),
        "reward_path: " + grading["reward_path"],
        "aggregation:",
        "  mode: " + mode,
        "checkers:",
    ]
    for item in g["checkers"]:
        kind = item["kind"]
        if kind not in KINDS:
            raise SystemExit("checker " + item["id"] + " carries an unknown kind")
        if not REASON_CODE.match(item["zero_reason"]):
            raise SystemExit("checker " + item["id"] + " carries a zero_reason that is not lowercase kebab")
        carrier = os.path.join(ROOT, item["reached_by"])
        if not os.path.isfile(carrier):
            raise SystemExit("checker " + item["id"] + " names a carrier that does not exist")
        carrier_bytes = open(carrier, encoding="utf-8").read()
        for field in ("zero_reason", "selector"):
            if item[field] not in carrier_bytes:
                raise SystemExit(
                    "checker " + item["id"] + " declares a " + field
                    + " the carrier " + item["reached_by"] + " never emits")
        lines.append("  - id: " + item["id"])
        lines.append("    reduction: " + kind)
        lines.append("    statement: " + json.dumps(one_line(item["asserts"])))
        lines.append("    reached_by: " + item["reached_by"])
        lines.append("    selector: " + item["selector"])
        lines.append("    zero_reason: " + item["zero_reason"])
        lines.append("    required: true")
        lines.append("    live_state_read: " + json.dumps(one_line(item["live_state_read"])))
    return "\n".join(lines) + "\n"


def gen_rubrics_jsonl(g):
    out = []
    for item in g["trajectory_rubrics"]:
        out.append(json.dumps({"id": item["id"], "rubric": one_line(item["rubric"])}, sort_keys=True))
    return "\n".join(out) + "\n"


def gen_solution_rubrics_json(g):
    spec = g["solution_rubric"]
    items = []
    each = float(spec["compiled_weight_each"])
    for checker in g["checkers"]:
        items.append({
            "id": checker["id"],
            "dimension": "outcome",
            "weight": each,
            "evaluation_target": "telemetry_record",
            "criterion": one_line(checker["asserts"]),
            "judgment": "Decided by the compiled test of the same id in tests/test_output.py.",
            "evidence": ["telemetry_record", "verifier_score"],
            "mode": "compiled",
        })
    for judged in spec["judged"]:
        items.append({
            "id": judged["id"],
            "dimension": judged["dimension"],
            "weight": float(judged["weight"]),
            "evaluation_target": judged["evaluation_target"],
            "criterion": one_line(judged["criterion"]),
            "judgment": one_line(judged["judgment"]),
            "evidence": list(judged["evidence"]),
            "mode": "judged",
            "residue": one_line(judged["residue"]),
        })
    total = sum(i["weight"] for i in items)
    compiled = sum(i["weight"] for i in items if i["mode"] == "compiled")
    payload = {
        "banner": BANNER,
        "source": SOURCE_NOTE,
        "compilation_floor": float(spec["compilation_floor"]),
        "compiled_weight_share": round(compiled / total, 6),
        "total_weight": round(total, 6),
        "evaluation_targets": spec["evaluation_targets"],
        "items": items,
    }
    if payload["compiled_weight_share"] < payload["compilation_floor"]:
        raise SystemExit("compiled weight share is below the declared floor")
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def gen_test_output_py(g):
    ids = [c["id"] for c in g["checkers"]]
    body = [
        '"""' + BANNER,
        "",
        SOURCE_NOTE,
        "",
        "One compiled test per checker, plus the reward range assertion. Each test",
        "reads the outcome map grade.py wrote, so nothing here rests on the author's",
        'word."""',
        "",
        "import json",
        "import os",
        "import sys",
        "",
        "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))",
        "",
        "from checkers import outcomes",
        "",
        "CHECKER_IDS = " + json.dumps(ids, indent=4).replace("\n", "\n") ,
        "",
        "",
        "def _o():",
        "    return outcomes.load()",
        "",
        "",
        "def test_every_checker_reported():",
        "    reported = _o()",
        "    missing = [c for c in CHECKER_IDS if c not in reported]",
        "    assert not missing, 'grade.py reported no outcome for ' + repr(missing)",
        "",
    ]
    for cid in ids:
        body.extend([
            "",
            "def test_" + cid + "():",
            "    assert _o()[" + json.dumps(cid) + "] is True",
            "",
        ])
    body.extend([
        "",
        "def test_reward_is_one_float_on_the_unit_interval():",
        "    path = os.environ.get('BIA_SCORE_DETAIL', '/logs/verifier/score_detail.json')",
        "    with open(path) as handle:",
        "        payload = json.load(handle)",
        "    score = payload['score']",
        "    assert isinstance(score, float), 'reward must be a single float'",
        "    assert 0.0 <= score <= 1.0, 'reward must sit on the closed interval zero to one'",
        "    assert payload['reason'], 'every score must carry a machine-readable reason'",
        "",
    ])
    return "\n".join(body)


def gen_truth_md(g):
    op = g["operating_point"]
    sp = op["scaled_point"]
    rw = g["reward"]
    parts = []
    parts.append("# TRUTH, private ground truth for BIA slot S04")
    parts.append("")
    parts.append("<!-- " + BANNER + " " + SOURCE_NOTE + " -->")
    parts.append("")
    parts.append("## What this slot is")
    parts.append("")
    parts.append(one_line(g["slot"]["family_note"]))
    parts.append("")
    parts.append("## Frozen surface")
    parts.append("")
    for row in g["slot"]["frozen"]:
        parts.append("- " + one_line(row))
    parts.append("")
    parts.append("## Free surface")
    parts.append("")
    parts.append("The submission is one JSON object carrying exactly these six integers, and nothing else in the bundle is writable by the agent.")
    parts.append("")
    for row in g["slot"]["free"]:
        parts.append("- " + one_line(row))
    parts.append("")
    parts.append("## The scaled operating point")
    parts.append("")
    parts.append(one_line(op["derivation"]))
    parts.append("")
    parts.append("| Quantity | Value |")
    parts.append("|---|---|")
    parts.append("| Session wallclock | " + str(op["session_hours"]) + " hours |")
    parts.append("| Attempts per session | " + str(op["attempts"]) + " |")
    parts.append("| Per attempt budget | " + str(op["per_attempt_minutes"]) + " minutes |")
    parts.append("| budget_hours | " + str(op["budget_hours"]) + " |")
    parts.append("| Accelerator | " + one_line(op["accelerator"]) + " |")
    parts.append("| Parameter budget | " + str(sp["parameter_budget"]) + " plus or minus " + str(sp["parameter_tolerance"]) + " |")
    parts.append("| Vocabulary | " + one_line(sp["vocabulary"]) + " |")
    parts.append("| Sequence length | " + str(sp["sequence_length"]) + " |")
    parts.append("| Batch sequences | " + str(sp["batch_sequences"]) + " |")
    parts.append("| Steps | " + str(sp["steps"]) + " |")
    parts.append("| Token budget | " + str(sp["token_budget"]) + " |")
    parts.append("| Arms per graded attempt | " + str(sp["arms_per_attempt"]) + " |")
    parts.append("| Runner deadline | " + str(sp["deadline_seconds"]) + " seconds |")
    parts.append("")
    parts.append(one_line(op["wall_clock_status"]))
    parts.append("")
    parts.append("## Reward")
    parts.append("")
    parts.append("`" + rw["expression"] + "`")
    parts.append("")
    parts.append(one_line(rw["why_paired"]))
    parts.append("")
    parts.append("## Reference allocation and the private solution")
    parts.append("")
    parts.append("The reference arm is the recalled answer, so the reference and the private solution together are the whole design argument, and both are shipped as JSON rather than as prose.")
    parts.append("")
    ref = json.load(open(os.path.join(ROOT, "tests", "frozen", "reference_arch.json")))
    sol = json.load(open(os.path.join(HERE, "solution_arch.json")))
    parts.append("| Arm | profile | n_layer | d_model | head_dim | n_head | n_kv_head | d_ff |")
    parts.append("|---|---|---|---|---|---|---|---|")
    for label, blob in (("reference", ref), ("private solution", sol)):
        for prof in ("full", "smoke"):
            a = blob[prof]
            parts.append("| " + label + " | " + prof + " | " + " | ".join(
                str(a[k]) for k in ("n_layer", "d_model", "head_dim", "n_head", "n_kv_head", "d_ff")) + " |")
    parts.append("")
    parts.append("## Defeat mechanism, stated as design intent")
    parts.append("")
    parts.append(one_line(g["defeat_mechanism"]["statement"]))
    parts.append("")
    parts.append("Status: " + g["defeat_mechanism"]["status"] + ".")
    parts.append("")
    parts.append(one_line(g["defeat_mechanism"]["discipline"]))
    parts.append("")
    parts.append("## Checkers and the kind each reduces to")
    parts.append("")
    parts.append("| Checker | Kind | Live-state read |")
    parts.append("|---|---|---|")
    for c in g["checkers"]:
        parts.append("| `" + c["id"] + "` | " + c["kind"] + " | " + one_line(c["live_state_read"]) + " |")
    parts.append("")
    parts.append("## Named gaps")
    parts.append("")
    for gap in g["named_gaps"]:
        parts.append("- `" + gap["id"] + "`: " + one_line(gap["statement"]))
    parts.append("")
    parts.append("## Cohort")
    parts.append("")
    parts.append("Designed against " + ", ".join(g["cohort"]["named"]) + ", valid to " + str(g["cohort"]["valid_to"]) + ". No solver registry digest is pinned anywhere in this project, so the cohort is named and not pinned, and that is recorded as a gap rather than smoothed over.")
    parts.append("")
    parts.append("## Disposition")
    parts.append("")
    parts.append(g["disposition"]["value"] + ". " + one_line(g["disposition"]["reason"]))
    parts.append("")
    return "\n".join(parts)


TARGETS = {
    "tests/checkers.yaml": gen_checkers_yaml,
    "tests/rubrics.jsonl": gen_rubrics_jsonl,
    "tests/test_output.py": gen_test_output_py,
    "solution/rubrics.json": gen_solution_rubrics_json,
    "solution/TRUTH.md": gen_truth_md,
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if committed bytes differ")
    args = ap.parse_args()
    g = load_grounding()
    drift = []
    for rel, fn in sorted(TARGETS.items()):
        want = fn(g)
        path = os.path.join(ROOT, rel)
        if args.check:
            current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
            if current != want:
                drift.append(rel)
            print(("ok    " if current == want else "DRIFT ") + rel)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as handle:
                handle.write(want)
            print("wrote " + rel)
    if args.check and drift:
        print("regeneration drift in: " + ", ".join(drift), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
