"""GENERATED FROM solution/grounding.yaml BY solution/recompute.py. DO NOT HAND-EDIT."""

from __future__ import annotations

KINDS = ('VALUE', 'EFFECT', 'ABSENCE', 'INVARIANT', 'ORDERING', 'DIVERGENCE')

CHECKERS = {
    'frozen_training_contract_held': {
        "kind": 'INVARIANT',
        "zero_reason": 'frozen-contract-moved',
        "reached_by": 'tests/grade.py',
        "selector": 'k_frozen_invariant',
        "live_state_read": 'every record of /telemetry/run_record.jsonl, its frozen block and its target_loss field',
        "asserts": 'the frozen operating point held identically across the whole run, every record of every phase',
    },
    'control_phase_sealed_before_submission_phase': {
        "kind": 'ORDERING',
        "zero_reason": 'control-seal-ordering-violated',
        "reached_by": 'tests/grade.py',
        "selector": 'k_ordering',
        "live_state_read": 'the record_index sequence and phase labels in /telemetry/run_record.jsonl',
        "asserts": 'the harness control phase was written and sealed before the first submission record, so the reward baseline was fixed before the submission was observed',
    },
    'no_weight_surgery_before_resume': {
        "kind": 'ABSENCE',
        "zero_reason": 'weight-surgery-detected',
        "reached_by": 'tests/grade.py',
        "selector": 'k_absence_weight_surgery',
        "live_state_read": '/telemetry/resume_digests.json, the model weight digest taken immediately before and immediately after recover returned',
        "asserts": 'the set of runs whose weights differ from the shipped checkpoint at step zero is empty',
    },
    'val_shard_digest_matches_manifest': {
        "kind": 'VALUE',
        "zero_reason": 'val-shard-digest-mismatch',
        "reached_by": 'tests/grade.py',
        "selector": 'k_value_val_shard',
        "live_state_read": 'the sha256 the verifier recomputes over the val.bin the run read, resolved through /telemetry/corpus_meta.json',
        "asserts": 'the recomputed validation shard digest equals the digest the fixture manifest binds',
    },
    'train_shard_digest_matches_manifest': {
        "kind": 'VALUE',
        "zero_reason": 'train-shard-digest-mismatch',
        "reached_by": 'tests/grade.py',
        "selector": 'k_value_train_shard',
        "live_state_read": 'the sha256 the verifier recomputes over the train.bin the run read, resolved through /telemetry/corpus_meta.json',
        "asserts": 'the recomputed training shard digest equals the digest the fixture manifest binds, so the data the graded steps consumed is the frozen corpus',
    },
    'recover_mutated_optimizer_state': {
        "kind": 'EFFECT',
        "zero_reason": 'recover-left-optimizer-unchanged',
        "reached_by": 'tests/grade.py',
        "selector": 'k_effect_recover',
        "live_state_read": '/telemetry/recover_effect.json, the optimizer fingerprint of the shipped checkpoint state beside the fingerprint of the optimizer recover returned',
        "asserts": 'calling recover changed live optimizer state in at least one named field rather than resuming the checkpoint state unaltered',
    },
    'graded_crossing_within_ceiling': {
        "kind": 'VALUE',
        "zero_reason": 'crossing-outside-ceiling',
        "reached_by": 'tests/grade.py',
        "selector": 'k_value_crossing',
        "live_state_read": 'the submission phase validation series in /telemetry/run_record.jsonl',
        "asserts": 'the produced step count at which the seed mean and every individual seed reach the target loss, and hold it, is bounded by the step ceiling',
    },
    'agent_report_agrees_with_verifier_recompute': {
        "kind": 'DIVERGENCE',
        "zero_reason": 'report-diverges-from-telemetry',
        "reached_by": 'tests/grade.py',
        "selector": 'k_divergence_report',
        "live_state_read": "submission/report.json beside the verifier's independent recomputation of the crossing from telemetry",
        "asserts": 'two independently derived step counts agree exactly',
    },
    'telemetry_hash_chain_unbroken': {
        "kind": 'INVARIANT',
        "zero_reason": 'telemetry-chain-broken',
        "reached_by": 'tests/grade.py',
        "selector": 'k_invariant_chain',
        "live_state_read": 'the record_index and chain field of every record of /telemetry/run_record.jsonl, rehashed by the verifier from the genesis seed',
        "asserts": 'the hash chain the runner wrote over the record sequence still recomputes, so no record was inserted, dropped, reordered or edited in place after it was written',
    },
    'telemetry_record_shape_matches_frozen_protocol': {
        "kind": 'INVARIANT',
        "zero_reason": 'record-shape-off-protocol',
        "reached_by": 'tests/grade.py',
        "selector": 'k_invariant_record_shape',
        "live_state_read": 'the phase, seed, kind and step fields of every record of /telemetry/run_record.jsonl against the seeds, eval_every and max_steps the fixture manifest binds',
        "asserts": 'each phase carries exactly one resume record and one phase_end record per seed, the submission phase covers exactly the frozen seed set, and every eval record sits at the resume step or at the frozen evaluation cadence above it',
    },
    'frozen_harness_code_unmodified': {
        "kind": 'INVARIANT',
        "zero_reason": 'harness-code-modified',
        "reached_by": 'tests/grade.py',
        "selector": 'k_invariant_harness_code',
        "live_state_read": 'the sha256 the verifier recomputes over the run_s08.py and s08_core.py files the run itself recorded loading, against the digests tests/frozen_digests.json binds and against the digests the runner recorded at load',
        "asserts": 'the two executable harness files the run imported are byte-identical to the frozen bundle bytes, at load and again at grading',
    },
    'shipped_checkpoint_bytes_unmodified': {
        "kind": 'VALUE',
        "zero_reason": 'checkpoint-bytes-modified',
        "reached_by": 'tests/grade.py',
        "selector": 'k_value_checkpoint_bytes',
        "live_state_read": 'the sha256 the verifier recomputes over the checkpoint file the run recorded loading, against the fixture_sha256 the manifest binds, the digest the runner recorded at load, and the frozen digest for a bound profile',
        "asserts": 'the shipped checkpoint was not rewritten before the run, during the run, or between the run and grading',
    },
    'fixture_manifest_bytes_unmodified': {
        "kind": 'VALUE',
        "zero_reason": 'manifest-bytes-modified',
        "reached_by": 'tests/grade.py',
        "selector": 'k_value_manifest_bytes',
        "live_state_read": 'the sha256 the verifier recomputes over both the manifest path the runner recorded and the manifest path the verifier grades from, against the digest the runner recorded at load and the frozen digest for a bound profile',
        "asserts": 'the manifest that supplied the target loss, the step ceiling and every bound digest is one file that did not change between load and grading',
    },
    'probe_budget_within_declared_allowance': {
        "kind": 'VALUE',
        "zero_reason": 'probe-budget-exceeded',
        "reached_by": 'tests/grade.py',
        "selector": 'k_value_probe_budget',
        "live_state_read": 'the probe_steps field of /telemetry/resume_digests.json beside the probe_steps field carried on every telemetry record of the same phase and seed, against the probe_batches_max the fixture manifest binds',
        "asserts": 'no run charged a negative or over-allowance probe count, and the two independent records of that count agree',
    },
    'stale_step_counter_not_resumed': {
        "kind": 'ABSENCE',
        "zero_reason": 'stale-step-counter-resumed',
        "reached_by": 'tests/grade.py',
        "selector": 'k_absence_stale_step',
        "live_state_read": 'the per-parameter step field of the recovered optimizer fingerprint in /telemetry/recover_effect.json, against the same field of the checkpoint fingerprint and against the checkpoint_step the fixture manifest reports',
        "asserts": "the set of parameters whose recovered state carries the checkpoint's recorded step counter, while that counter disagrees with the checkpoint step the manifest reports, is empty",
    },
    'optimizer_preconditioner_repaired': {
        "kind": 'EFFECT',
        "zero_reason": 'preconditioner-not-repaired',
        "reached_by": 'tests/grade.py',
        "selector": 'k_effect_preconditioner',
        "live_state_read": 'the per-parameter exp_avg_sq_rms field of the checkpoint fingerprint beside the recovered fingerprint in /telemetry/recover_effect.json',
        "asserts": "at least one parameter's Adam second moment differs from the value the checkpoint carried, so a recovery that touched only the step counter or only the param_groups does not pass as a repair",
    },
    'declared_hyperparameters_match_optimizer_in_force': {
        "kind": 'DIVERGENCE',
        "zero_reason": 'declared-hyperparameters-diverge',
        "reached_by": 'tests/grade.py',
        "selector": 'k_divergence_hyperparameters',
        "live_state_read": 'the optimizer block of submission/report.json beside the recovered param_groups recorded in /telemetry/recover_effect.json for every submission run',
        "asserts": 'the declared hyperparameters and the hyperparameters the machine record shows in force agree on every field the agent declared, and weight_decay is declared',
    },
    'recover_ran_outside_the_measuring_process': {
        "kind": 'INVARIANT',
        "zero_reason": 'recover-ran-inside-the-measuring-process',
        "reached_by": 'tests/grade.py',
        "selector": 'k_invariant_recover_isolation',
        "live_state_read": 'the recover_isolation block on every submission entry of /telemetry/resume_digests.json, comparing runner_pid against worker_pid and requiring mode subprocess with worker recover_worker.py',
        "asserts": 'no part of the measurement shared an interpreter with submitted bytes, so the evaluation the crossing is computed from was never reachable from the recovery',
    },
    'graded_record_authored_by_the_verifier': {
        "kind": 'VALUE',
        "zero_reason": 'graded-record-not-authored-by-the-verifier',
        "reached_by": 'tests/grade.py',
        "selector": 'k_value_record_origin',
        "live_state_read": 'the run_nonce and submission_sha256 fields of run_origin.json beside the graded telemetry, against the nonce held only in this verifier process and hashlib.sha256 over the deliverable on the verifier filesystem at grade time',
        "asserts": 'the graded record was produced by an execution this process started, so a planted, replayed or hand-authored record set fails however internally consistent its hash chain is',
    },
    'telemetry_chain_terminated_at_the_recorded_head': {
        "kind": 'INVARIANT',
        "zero_reason": 'telemetry-chain-not-terminated-at-the-recorded-head',
        "reached_by": 'tests/grade.py',
        "selector": 'k_invariant_chain_terminated',
        "live_state_read": 'the record count and terminal chain field of /telemetry/run_record.jsonl against record_count and chain_head in /telemetry/run_origin.json, which the runner writes outside the chain',
        "asserts": 'the record sequence is bound at both ends, so truncating the tail is detected even though a forward chain leaves every surviving link intact',
    },
    'agent_run_reproduces_under_verifier_execution': {
        "kind": 'DIVERGENCE',
        "zero_reason": 'agent-run-did-not-reproduce-under-verifier-execution',
        "reached_by": 'tests/grade.py',
        "selector": 'k_divergence_reproduction',
        "live_state_read": 'the submission and control validation series of the agent written /telemetry/run_record.jsonl beside the same series of the record this verifier executed for itself, against eval_every in the fixture manifest',
        "asserts": 'two records of the same frozen experiment produced by different producers agree, where one producer is reachable from the submission and the other is not',
    },
}
