# FORGE-CANARY-BEGIN
# 0: 0d57aabc3b3e5f1890f20afd8d647afd0b372a30a7aa9c260f16b4014394c9dc
# 1: 911a6d3a5719df7e7609030034e6664f37eb3d04400ccd2025c66c190d198453
# 2: 906b05b06a7851f2a720dde8c9ecb69c4f729d957bb5433d697a4c30439fe75e
# 3: 0d9f60a747a97e5eb90b66d3fc5547297f58dfb3739e65b0e22b21e02e1f3f63
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
