# FORGE-CANARY-BEGIN
# 0: 6aa9104dbeeb84fd2daf862d208aec36fe44dc4d474717027f01edb73f0676ee
# 1: ee49461a172922563d022a7cebed22dde01bc76ec18d3e1c0bf3e59e6835bb36
# 2: 32138dcd9761f9f1cb158c4c07437bfcb3c4aabca45d561935f2155d81cac805
# 3: 017728c4dc1678afce271a3afa16b1267b2829919ea0f017de7ceec4a01cd71a
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
