# FORGE-CANARY-BEGIN
# 0: 213c5420afd3502f9501218af904aee68c16abdf0e91a3382d9da654ed667a6e
# 1: 64282e3aa97a20d8de29933a195f876d601a53b5ed33c57589bfd227f033db8f
# 2: f31555c94e950e25aa43d211873e9f82ece7bc18cbe602cf11088d138d81c61d
# 3: e3ef4104977b27882455667b3f58abb1a2639b4a52250cec418e150c77c4331d
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
