# FORGE-CANARY-BEGIN
# 0: 71ac5045570e4faab1691980f61225e53b091577d61a7e1904a501ddd9d341d7
# 1: 1bbf47332ea41cbd414124cc8996105386c6641289459b7822d9eb817ab68258
# 2: 1d461767dfa186153d0c9ad725d331ca9a661ffd036f0cd9e728ebacb7a19013
# 3: e48e95ce12f0517b6aa8b91450fe9ade425b13d7a294768546f9898365dde1c2
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
