"""Compiled rubric tests.

GENERATED SECTION. DO NOT HAND-EDIT.

Generated by solution/recompute.py from solution/grounding.yaml.
Identifiers only. Criterion prose lives in solution/rubrics.json and stays private.
"""
from __future__ import annotations

import json
import os
import pathlib

REWARD = pathlib.Path(os.environ.get("BIA_REWARD_PATH", "/logs/verifier/reward.txt"))
RECORD = pathlib.Path(os.environ.get("BIA_REWARD_RECORD", "/logs/verifier/record.json"))


def _payload() -> dict:
    return json.loads(RECORD.read_text())


def test_reward_file_written():
    assert REWARD.is_file()


def test_bound_reward_is_one_float_agreeing_with_the_record():
    value = float(REWARD.read_text().strip())
    assert 0.0 <= value <= 1.0
    assert abs(value - float(_payload()["reward"])) < 1e-6


def test_reward_shape():
    p = _payload()
    assert 0.0 <= p["reward"] <= 1.0
    assert p["pass"] in (0, 1)
    assert isinstance(p["reason"], str) and p["reason"]


def test_zero_reward_carries_reason():
    p = _payload()
    if p["reward"] == 0.0:
        assert p["reason"] != ""


def test_unmeasured_anchors_never_pass():
    p = _payload()
    if p["reason"] == "anchors-unmeasured":
        assert p["pass"] == 0 and p["reward"] == 0.0


def test_rubric_r1_present():
    # R1 :: verifier_token_count
    p = _payload()
    assert "checkers" in p

def test_rubric_r2_present():
    # R2 :: verifier_loss_curve
    p = _payload()
    assert "checkers" in p

def test_rubric_r3_present():
    # R3 :: verifier_loss_curve
    p = _payload()
    assert "checkers" in p

def test_rubric_r4_present():
    # R4 :: verifier_loss_curve
    p = _payload()
    assert "checkers" in p

def test_rubric_r5_present():
    # R5 :: container_execution_record
    p = _payload()
    assert "checkers" in p

def test_rubric_r6_present():
    # R6 :: submitted_script_source
    p = _payload()
    assert "checkers" in p
