# FORGE-CANARY-BEGIN
# 0: 1136e6d4f924fc88b7e85d4d4f130a3ea89db3cb3275fdda7fd6ed1f7cf0a725
# 1: 2c38fc7330a0e0e2b074849a9b240dd12a214648855c652e14bc05bccd1ee782
# 2: 9a94a25c57f11c4b893bfc113777d729befad19b834d313b6474d95d31d53636
# 3: 9d8df1924776cda7c54e464c581aadff6627b234dd389585a6152a0ca53361ff
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"

# THE INSTALL, WRITTEN SO THE DESTINATION IS LEGIBLE IN THESE FROZEN BYTES.
# Both branches name the one path ${submission} already resolves to, and they
# are written out rather than folded into a single `cp ... "${submission}"`
# because the folded form states its destination only through an expansion. A
# reader of this file - the control harness among them - then has no path to
# read and falls back to whichever directory this phase happened to write into,
# which resolves the submission to the DIRECTORY /app while tests/grade.py opens
# a FILE. The default branch below states the literal path task.toml binds as
# the graded artifact and tests/grade.py opens when nothing overrides it, so
# both halves of that join are readable in the frozen bytes of both files.
if [ -n "${OER16_SUBMISSION:-}" ]; then
  cp "${here}/reference.py" "${OER16_SUBMISSION}"
else
  cp "${here}/reference.py" "/app/submission.py"
fi

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
