# FORGE-CANARY-BEGIN
# 0: 303d2fd079cfcc8c8cad0dc43fe76cfb7d73b649c01542d633f745ca65f178d6
# 1: aba398c05c7e3b820c6ab8b84c31deb197593c063ac9ab3f6f3714feffc206cc
# 2: 773e7c2da6422977e1c118d81bdc7127f84883f673c7be63d47f7eb49259f225
# 3: b01ccc4fce1c9dcf069614383a088baa86f5d9f06906dccc0b7b3f36aae743c8
# FORGE-CANARY-END
#!/usr/bin/env python3
"""Derive every generated artifact in this bundle from solution/grounding.yaml.

One private source, one deriving script. What this produces:

  solution/golden_trajectory.json   the reference path through the gate chain
  tests/fixtures/*.json             every checker fixture, clean and planted
  solution/solve.sh                 the solver entry point
  solution/TRUTH.md                 the held-out account of the answer
  solution/rubrics.json             the solution graded against its reference
  tests/test_output.py              one compiled test per checker

What this NEVER does: invoke a model, open a socket, read a clock, read a
locale, or consult a random source. Every number below is either read out of
grounding.yaml or computed from it by arithmetic and by the verifier's own
probe. Running this twice over frozen bytes produces byte-identical output,
which `--check` asserts.

Usage:
    python3 solution/recompute.py            # write
    python3 solution/recompute.py --check    # fail if any generated byte drifted
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import yaml

BUNDLE = Path(__file__).resolve().parents[1]
GROUNDING = BUNDLE / "solution" / "grounding.yaml"
TESTS = BUNDLE / "tests"
FIXTURES = TESTS / "fixtures"
SOLUTION = BUNDLE / "solution"

BANNER = "GENERATED SECTION. DO NOT HAND-EDIT."
SOURCE_LINE = "Source: solution/grounding.yaml. Regenerate with: python3 solution/recompute.py"

sys.path.insert(0, str(TESTS))
sys.path.insert(0, str(SOLUTION))

import checkers  # noqa: E402
import corpus_rules  # noqa: E402
import probe  # noqa: E402
import reference  # noqa: E402
from corpus import loader  # noqa: E402

# The rule shipped to the agent, imported here only to derive the fixture that
# proves an unchanged submission is behaviourally present in the corpus. The
# GRADING process never imports it; this is a generation-time derivation.
sys.path.insert(0, str(BUNDLE / "environment"))
import update_rule as shipped_rule  # noqa: E402


def source() -> dict:
    return yaml.safe_load(GROUNDING.read_text(encoding="utf-8"))


def digest_of(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Telemetry construction. Every field here is one the VERIFIER produces.
# ---------------------------------------------------------------------------


def loss_at(step: int, crossing: int, interval: int, target: float) -> float:
    """A monotone series crossing `target` exactly at `crossing`.

    At `crossing - interval` the value is the target itself, which is NOT below
    it, so the crossing lands where the name says it does and never one point
    early.
    """
    return round(target - (step - crossing + interval) * 0.0002, 6)


def eval_points(seed: int, crossing: int, geo: dict, last_step: int, custody: str) -> list:
    interval = int(geo["eval_interval"])
    target = float(geo["target_loss"])
    rows = []
    for step in range(interval, last_step + 1, interval):
        raw = loss_at(step, crossing, interval, target)
        rows.append(
            {
                "step": step,
                "loss_raw": raw,
                "graded_loss": raw,
                "loss_source": "verifier-holdout-eval",
                "smoothing": "none",
                "weights_digest": digest_of("weights:" + str(seed) + ":" + str(step)),
                "weights_custody": custody,
            }
        )
    return rows


def seed_run(seed: int, crossing: int, geo: dict, last_step: int, custody: str) -> dict:
    points = eval_points(seed, crossing, geo, last_step, custody)
    return {
        "seed": seed,
        "claimed_graded_step": crossing,
        "halt_reason": "completed",
        "last_eval_step": last_step,
        "eval_points": points,
        "harness_weight_ledger": [
            {"step": row["step"], "weights_digest": row["weights_digest"], "custody": custody}
            for row in points
        ],
    }


def probe_block(rule, set_name: str, geo: dict) -> dict:
    """The verifier's own probe outcome over a rule. Computed, never asserted."""
    first = probe.signature(rule, set_name)
    second = probe.signature(rule, set_name)
    signatures = loader.signatures(corpus_rules.build, probe, set_name)
    found = probe.nearest(first["transcript"], signatures)
    pinned = loader.pinned_digest()
    return {
        "probe_set": set_name,
        "pass_a": {"transcript": first["transcript"], "digest": first["digest"]},
        "pass_b": {"transcript": second["transcript"], "digest": second["digest"]},
        "transcript_digest": first["digest"],
        "harness_deltas_digest": first["digest"],
        "corpus_pinned_digest": pinned,
        "corpus_digest_at_verdict": pinned,
        "corpus_entries": len(signatures),
        "behavioural_margin": float(geo["behavioural_margin"]),
        "nearest_corpus_id": found["nearest_corpus_id"],
        "min_behavioural_distance": found["min_behavioural_distance"],
    }


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def telemetry(doc: dict, steps_key: str, rule, anchors_state: str = "fixture", rule_path: Path = None) -> dict:
    geo = doc["graded_quantity"]
    state = dict(doc["drift_state_final"])
    interval = int(geo["eval_interval"])
    window = int(state["sustain_window"])
    crossings = list(doc["seed_step_lists"][steps_key])
    last_step = max(crossings) + (window + 2) * interval
    pair = doc["fixture_anchor_pair"]
    tree = digest_of("grading-tree-sealed")
    return {
        "schema": checkers.SCHEMA,
        "produced_by": "verifier",
        "fixture": steps_key,
        "drift_state": state,
        "anchors": {
            "state": anchors_state,
            "baseline_metric": pair["baseline_metric"] if anchors_state != "absent" else None,
            "target_metric": pair["target_metric"] if anchors_state != "absent" else None,
            "fixture_only": True,
            "not_an_anchor": True,
            "bound_anchors_state": "absent",
            "bound_anchors_gap": "gap-oer-per-family-anchors-unmeasured",
        },
        "target_loss": float(geo["target_loss"]),
        "eval_interval": interval,
        "seed_runs": [
            seed_run(index, crossing, geo, last_step, state["weight_custody"])
            for index, crossing in enumerate(crossings)
        ],
        "submission_binding": {
            "path": rule_path.relative_to(BUNDLE).as_posix() if rule_path else None,
            "sha256": file_sha256(rule_path) if rule_path else None,
            "note": "the probed rule's bytes, bound into the fixture so the accepting half proves the checkers accept THIS file and not merely some file",
        },
        "probe": probe_block(rule, state["probe_input_set"], geo),
        "order_log": [
            {"event": "submission-exit", "seq": 1},
            {"event": "process-group-killed", "seq": 2},
            {"event": "truth-computed", "seq": 3},
        ],
        "grading_tree": {"digest_open": tree, "digest_close": tree, "upper_entries": ["logs/run.jsonl"]},
        "graded_metric_provenance": [
            {"field": name, "producer": "verifier"} for name in sorted(checkers.GRADED_FIELDS)
        ],
        "verdict_order": {"corpus_pinned_at": 1, "verdict_taken_at": 2},
    }


# ---------------------------------------------------------------------------
# The fixture set. One clean accepting fixture, two continuity fixtures, one
# planted-defect fixture per checker, and one stale control per silent drift
# mutation plus the anchors-absent control.
# ---------------------------------------------------------------------------


def mutate(base: dict, apply) -> dict:
    row = json.loads(json.dumps(base, sort_keys=True))
    apply(row)
    return row


def _plant_truth_before_exit(row):
    row["fixture"] = "defect_truth_before_exit"
    row["order_log"] = [
        {"event": "truth-computed", "seq": 1},
        {"event": "submission-exit", "seq": 2},
        {"event": "process-group-killed", "seq": 3},
    ]


def _plant_grading_tree_mutated(row):
    row["fixture"] = "defect_grading_tree_mutated"
    row["grading_tree"]["digest_close"] = digest_of("grading-tree-moved")
    row["grading_tree"]["upper_entries"] = ["logs/run.jsonl", "tests/checkers.py"]


def _plant_submission_number(row):
    row["fixture"] = "defect_submission_number_on_graded_path"
    row["graded_metric_provenance"][0]["producer"] = "submission"


def _plant_readout_smoothed(row):
    row["fixture"] = "defect_readout_smoothed"
    for run in row["seed_runs"]:
        for point in run["eval_points"]:
            point["smoothing"] = "ema-0.9"
            point["graded_loss"] = round(point["loss_raw"] - 0.05, 6)


def _plant_early_stop(row):
    row["fixture"] = "defect_early_stop"
    for run in row["seed_runs"]:
        run["halt_reason"] = "early-stop"
        cut = int(run["claimed_graded_step"])
        run["eval_points"] = [p for p in run["eval_points"] if p["step"] <= cut]
        run["harness_weight_ledger"] = [p for p in run["harness_weight_ledger"] if p["step"] <= cut]
        run["last_eval_step"] = cut


def _plant_not_sustained(row):
    row["fixture"] = "defect_crossing_not_sustained"
    target = float(row["target_loss"])
    for run in row["seed_runs"]:
        for point in run["eval_points"]:
            if point["step"] > int(run["claimed_graded_step"]):
                point["loss_raw"] = round(target + 0.01, 6)
                point["graded_loss"] = point["loss_raw"]


def _plant_weights_not_owned(row):
    row["fixture"] = "defect_weights_not_harness_owned"
    for run in row["seed_runs"]:
        for point in run["eval_points"]:
            if point["step"] >= int(run["claimed_graded_step"]):
                point["weights_custody"] = "submission-selected-checkpoint"


def _plant_probe_nondeterministic(row):
    row["fixture"] = "defect_probe_nondeterministic"
    rows = json.loads(json.dumps(row["probe"]["pass_b"]["transcript"]))
    rows[0][0] = round(rows[0][0] + 0.001, 6)
    row["probe"]["pass_b"]["transcript"] = rows


def _plant_transcript_divergence(row):
    row["fixture"] = "defect_probe_transcript_diverges"
    row["probe"]["harness_deltas_digest"] = digest_of("harness-watched-something-else")


def _plant_verdict_predates_pin(row):
    row["fixture"] = "defect_novelty_verdict_predates_pin"
    row["verdict_order"] = {"corpus_pinned_at": 5, "verdict_taken_at": 2}


def _plant_stale_probe_set(row):
    row["fixture"] = "control_stale_probe_set"
    row["probe"]["probe_set"] = "probe-set-a"


def _plant_stale_sustain_window(row):
    row["fixture"] = "control_stale_sustain_window"
    target = float(row["target_loss"])
    interval = int(row["eval_interval"])
    for run in row["seed_runs"]:
        crossing = int(run["claimed_graded_step"])
        for point in run["eval_points"]:
            if point["step"] > crossing + 2 * interval:
                point["loss_raw"] = round(target + 0.01, 6)
                point["graded_loss"] = point["loss_raw"]


def _plant_stale_weight_custody(row):
    row["fixture"] = "control_stale_weight_custody"
    for run in row["seed_runs"]:
        for point in run["eval_points"]:
            point["weights_custody"] = "harness-owned"
        for point in run["harness_weight_ledger"]:
            point["custody"] = "harness-owned"


def _plant_anchors_absent(row):
    row["fixture"] = "control_anchors_absent"
    row["anchors"]["state"] = "absent"
    row["anchors"]["baseline_metric"] = None
    row["anchors"]["target_metric"] = None


def fixture_set(doc: dict) -> dict:
    ref_rule = reference.build_update_rule((8, 8), {})
    ref_path = SOLUTION / "reference.py"
    shipped = shipped_rule.build_update_rule((8, 8), {})
    shipped_path = BUNDLE / "environment" / "update_rule.py"

    clean = telemetry(doc, "clean_accepting", ref_rule, rule_path=ref_path)
    clean["fixture"] = "clean_accepting"
    partial = telemetry(doc, "partial_continuous", ref_rule, rule_path=ref_path)
    partial["fixture"] = "partial_continuous"
    ramp = telemetry(doc, "margin_ramp_continuous", ref_rule, rule_path=ref_path)
    ramp["fixture"] = "margin_ramp_continuous"
    floor = telemetry(doc, "separation_below_floor", ref_rule, rule_path=ref_path)
    floor["fixture"] = "defect_separation_below_floor"

    # The unchanged shipped rule. Behaviourally present in the corpus, which is
    # what makes it the no-op negative control rather than a starting point.
    noop = telemetry(doc, "clean_accepting", shipped, rule_path=shipped_path)
    noop["fixture"] = "defect_behaviour_matches_corpus"

    out = {
        "clean_accepting": clean,
        "partial_continuous": partial,
        "margin_ramp_continuous": ramp,
        "defect_separation_below_floor": floor,
        "defect_behaviour_matches_corpus": noop,
    }
    for name, plant in (
        ("defect_truth_before_exit", _plant_truth_before_exit),
        ("defect_grading_tree_mutated", _plant_grading_tree_mutated),
        ("defect_submission_number_on_graded_path", _plant_submission_number),
        ("defect_readout_smoothed", _plant_readout_smoothed),
        ("defect_early_stop", _plant_early_stop),
        ("defect_crossing_not_sustained", _plant_not_sustained),
        ("defect_weights_not_harness_owned", _plant_weights_not_owned),
        ("defect_probe_nondeterministic", _plant_probe_nondeterministic),
        ("defect_probe_transcript_diverges", _plant_transcript_divergence),
        ("defect_novelty_verdict_predates_pin", _plant_verdict_predates_pin),
        ("control_stale_probe_set", _plant_stale_probe_set),
        ("control_stale_sustain_window", _plant_stale_sustain_window),
        ("control_stale_weight_custody", _plant_stale_weight_custody),
        ("control_anchors_absent", _plant_anchors_absent),
    ):
        out[name] = mutate(clean, plant)
    return out


# The fixture that carries each checker's REJECTING half, and the reason it
# must produce. Read by the compiled tests and by seed/tasks/OER-05/adequacy.py.
REJECTING_HALF = (
    ("truth_computed_after_submission_exit", "defect_truth_before_exit", "truth-computed-before-submission-exit"),
    ("grading_tree_not_writable_from_submission", "defect_grading_tree_mutated", "grading-tree-mutated"),
    ("no_submission_number_on_graded_metric", "defect_submission_number_on_graded_path", "submission-supplied-number-on-graded-path"),
    ("graded_crossing_recomputed_unsmoothed", "defect_readout_smoothed", "readout-smoothing-on-graded-path"),
    ("early_stop_yields_no_crossing", "defect_early_stop", "early-stop-without-sustained-window"),
    ("crossing_sustained_across_scheduled_evals", "defect_crossing_not_sustained", "crossing-not-sustained"),
    ("evaluated_weights_are_harness_owned", "defect_weights_not_harness_owned", "weights-not-harness-owned"),
    ("behavioural_probe_deterministic", "defect_probe_nondeterministic", "probe-digest-nondeterministic"),
    ("probe_transcript_bound_to_training_deltas", "defect_probe_transcript_diverges", "probe-transcript-diverges-from-harness-deltas"),
    ("corpus_pinned_before_novelty_verdict", "defect_novelty_verdict_predates_pin", "novelty-verdict-predates-corpus-pin"),
    ("behavioural_novelty_clears_corpus", "defect_behaviour_matches_corpus", "behaviour-matches-corpus-entry"),
    ("multi_seed_separation_clears_margin", "defect_separation_below_floor", "separation-below-noise-floor"),
)

STALE_CONTROLS = (
    ("ctl-novelty-verdict-taken-before-corpus-pin", "defect_novelty_verdict_predates_pin", "novelty-verdict-predates-corpus-pin"),
    ("ctl-novelty-verdict-carried-from-probe-set-a", "control_stale_probe_set", "behaviour-matches-corpus-entry"),
    ("ctl-crossing-sustained-under-two-point-window", "control_stale_sustain_window", "crossing-not-sustained"),
    ("ctl-weights-accepted-under-pre-mutation-custody", "control_stale_weight_custody", "weights-not-harness-owned"),
)


# ---------------------------------------------------------------------------
# Generated artifacts.
# ---------------------------------------------------------------------------


def golden_trajectory(doc: dict, fixtures: dict) -> str:
    import grade as grader

    rows = []
    for name in ("clean_accepting", "partial_continuous", "margin_ramp_continuous"):
        document = grader.grade(fixtures[name])
        rows.append(
            {
                "fixture": name,
                "reward": document["reward"],
                "reason": document["reason"],
                "graded_steps_per_seed": document["metric"]["graded_steps_per_seed"],
                "mean_raw": document["metric"]["mean_raw"],
                "half_spread": document["metric"]["half_spread"],
                "separation": document["metric"]["separation"],
                "confidence": document["metric"]["confidence"],
            }
        )
    payload = {
        "banner": BANNER,
        "source": SOURCE_LINE,
        "slot": "OER-05",
        "note": "The reference path through the real gate chain. Reward growth is visible across the three fixtures, so the reward is continuous and never binary.",
        "anchors_state": "absent",
        "anchors_gap": "gap-oer-per-family-anchors-unmeasured",
        "fixture_anchor_pair_is_not_an_anchor": True,
        "steps": rows,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def solve_sh(doc: dict) -> str:
    ref = doc["reference"]
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "# " + BANNER,
            "# " + SOURCE_LINE,
            "#",
            "# The solver entry point. It installs the reference update rule over the",
            "# one file the agent is allowed to edit and does nothing else, because the",
            "# frozen axes are frozen and this script must not touch one.",
            "set -euo pipefail",
            "",
            'BUNDLE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"',
            'WORKSPACE="${OER05_WORKSPACE:-${BUNDLE}/environment}"',
            "",
            "# The rule class is " + str(ref["rule_class"]) + ", exposing " + str(ref["entry_point"]) + ".",
            'install -m 0644 "${BUNDLE}/' + str(ref["path"]) + '" "${WORKSPACE}/update_rule.py"',
            "",
            'echo "installed the reference update rule at ${WORKSPACE}/update_rule.py"',
            "",
        ]
    )


def truth_md(doc: dict, fixtures: dict, golden: dict) -> str:
    ref = doc["reference"]
    lines = [
        "# TRUTH.md — OER-05, held out",
        "",
        BANNER,
        "",
        SOURCE_LINE,
        "",
        "## The answer",
        "",
        "The reference update rule is `" + str(ref["rule_class"]) + "` in `" + str(ref["path"]) + "`.",
        "It clears the behavioural novelty gate by doing three things no pinned corpus",
        "entry does:",
        "",
    ]
    for lever in ref["novelty_levers"]:
        lines.append("- " + str(lever))
    lines += [
        "",
        "None of the three is a source-level difference. Each changes the DELTA pattern",
        "the verifier's probe records, which is the only thing the gate compares.",
        "",
        "## Measured behavioural distance",
        "",
        "| probe set | nearest corpus entry | distance | bound margin |",
        "|---|---|---|---|",
    ]
    for set_name in ("probe-set-a", "probe-set-b"):
        rule = reference.build_update_rule((8, 8), {})
        signatures = loader.signatures(corpus_rules.build, probe, set_name)
        found = probe.nearest(probe.signature(rule, set_name)["transcript"], signatures)
        lines.append(
            "| "
            + set_name
            + " | "
            + str(found["nearest_corpus_id"])
            + " | "
            + str(found["min_behavioural_distance"])
            + " | "
            + str(doc["graded_quantity"]["behavioural_margin"])
            + " |"
        )
    lines += [
        "",
        "The rule shipped to the agent in `environment/update_rule.py` is heavy-ball",
        "momentum, whose measured distance to the corpus entry `momentum` is exactly",
        "0.0 on both probe sets. Submitting it unchanged scores zero with the reason",
        "`behaviour-matches-corpus-entry`. Paraphrasing its source moves that distance",
        "by nothing at all, which is the property the gate exists to have.",
        "",
        "## The reference path through the real gate chain",
        "",
        "| fixture | reward | reason |",
        "|---|---|---|",
    ]
    for row in golden["steps"]:
        lines.append("| " + row["fixture"] + " | " + repr(row["reward"]) + " | " + row["reason"] + " |")
    lines += [
        "",
        "Three different rewards over three fixtures is the reward-continuity evidence:",
        "the score moves with the result rather than flipping at a line.",
        "",
        "## Anchors",
        "",
        "This family's anchors are UNMEASURED. `baseline_metric` and `target_metric`",
        "are absent from this bundle and no value is invented for them. The gap is",
        "`gap-oer-per-family-anchors-unmeasured`. The two numbers in",
        "`grounding.yaml` under `fixture_anchor_pair` are fixture arithmetic",
        "exercisers, are labelled `not_an_anchor`, and carry no authority.",
        "",
        "On the live graded path a telemetry record whose anchor pair is absent is",
        "refused with the machine-readable reason `anchor-pair-absent`.",
        "",
        "## What this does not establish",
        "",
        str(ref["what_acceptance_does_not_establish"]).strip(),
        "",
    ]
    return "\n".join(lines)


def rubrics_json(doc: dict) -> str:
    payload = {
        "banner": BANNER,
        "source": SOURCE_LINE,
        "slot": "OER-05",
        "judges": "the solution against its reference answer",
        "distinct_from": "tests/rubrics.jsonl, which judges the trajectory. Neither substitutes for the other.",
        "criteria": [
            {"id": row["id"], "criterion": row["criterion"], "weight": row["weight"]}
            for row in doc["solution_rubric_criteria"]
        ],
        "total_weight": sum(int(row["weight"]) for row in doc["solution_rubric_criteria"]),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def test_output_py(doc: dict) -> str:
    lines = [
        "#!/usr/bin/env python3",
        '"""' + BANNER,
        "",
        SOURCE_LINE,
        "",
        "One compiled test per graded checker, each proving BOTH halves: the clean",
        "fixture accepts, and that checker's planted-defect fixture produces exactly",
        "that checker's own zero_reason. Two of the twelve carry their rejecting half",
        "on a planted fixture because no submission can fire them while the isolation",
        "boundary holds; that substitution is recorded in tests/checkers.yaml and in",
        "seed/tasks/OER-05/feasibility.yaml.",
        "",
        "Runs under pytest and also standalone as `python3 tests/test_output.py`.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "import sys",
        "from pathlib import Path",
        "",
        "HERE = Path(__file__).resolve().parent",
        "if str(HERE) not in sys.path:",
        "    sys.path.insert(0, str(HERE))",
        "",
        "import checkers  # noqa: E402",
        "import grade  # noqa: E402",
        "",
        "FIXTURES = HERE / 'fixtures'",
        "",
        "",
        "def load(name):",
        "    return json.loads((FIXTURES / (name + '.json')).read_text(encoding='utf-8'))",
        "",
        "",
        "def verdict(selector, ctx):",
        "    return getattr(checkers, 'check_' + selector)(ctx)",
        "",
        "",
    ]
    for ident, fixture, reason in REJECTING_HALF:
        lines += [
            "def test_" + ident + "():",
            "    clean = verdict('" + ident + "', load('clean_accepting'))",
            "    assert clean.ok, 'accepting half failed: ' + clean.detail",
            "    planted = verdict('" + ident + "', load('" + fixture + "'))",
            "    assert not planted.ok, 'rejecting half did not fire'",
            "    assert planted.reason == '" + reason + "', planted.reason",
            "",
            "",
        ]
    lines += [
        "def test_clean_fixture_reaches_full_reward():",
        "    document = grade.grade(load('clean_accepting'))",
        "    assert document['reward'] == 1.0, document",
        "    assert document['reason'] == 'graded', document",
        "",
        "",
        "def test_reward_is_continuous_and_never_binary():",
        "    rewards = [grade.grade(load(name))['reward'] for name in (",
        "        'clean_accepting', 'partial_continuous', 'margin_ramp_continuous',",
        "    )]",
        "    assert rewards[0] == 1.0, rewards",
        "    assert 0.0 < rewards[2] < rewards[1] < rewards[0], rewards",
        "",
        "",
        "def test_absent_anchors_are_refused_rather_than_substituted():",
        "    document = grade.grade(load('control_anchors_absent'))",
        "    assert document['reward'] == 0.0, document",
        "    assert document['reason'] == 'anchor-pair-absent', document",
        "",
        "",
    ]
    for ident, fixture, reason in STALE_CONTROLS:
        safe = ident.replace("-", "_")
        lines += [
            "def test_stale_control_" + safe + "():",
            "    document = grade.grade(load('" + fixture + "'))",
            "    assert document['reward'] == 0.0, document",
            "    assert document['reason'] == '" + reason + "', document",
            "",
            "",
        ]
    lines += [
        "def main():",
        "    failures = []",
        "    for name, fn in sorted(globals().items()):",
        "        if not name.startswith('test_') or not callable(fn):",
        "            continue",
        "        try:",
        "            fn()",
        "        except AssertionError as exc:",
        "            failures.append(name + ': ' + str(exc))",
        "    for row in failures:",
        "        print('FAIL ' + row)",
        "    print(('FAILED ' + str(len(failures))) if failures else 'compiled tests: all passed')",
        "    return 1 if failures else 0",
        "",
        "",
        "if __name__ == '__main__':",
        "    raise SystemExit(main())",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Emission.
# ---------------------------------------------------------------------------


def artifacts() -> dict:
    doc = source()
    fixtures = fixture_set(doc)
    out = {}
    for name, payload in sorted(fixtures.items()):
        out[FIXTURES / (name + ".json")] = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    golden_text = golden_trajectory(doc, fixtures)
    out[SOLUTION / "golden_trajectory.json"] = golden_text
    out[SOLUTION / "solve.sh"] = solve_sh(doc)
    out[SOLUTION / "TRUTH.md"] = truth_md(doc, fixtures, json.loads(golden_text))
    out[SOLUTION / "rubrics.json"] = rubrics_json(doc)
    out[TESTS / "test_output.py"] = test_output_py(doc)
    return out


def main(argv) -> int:
    check = "--check" in argv
    rows = artifacts()
    drifted = []
    for path, text in sorted(rows.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != text:
            drifted.append(path.relative_to(BUNDLE).as_posix())
            if not check:
                path.write_text(text, encoding="utf-8")
    if check:
        if drifted:
            print("DRIFTED: " + ", ".join(sorted(drifted)))
            return 1
        print("byte-identical over " + str(len(rows)) + " generated artifact(s)")
        return 0
    (SOLUTION / "solve.sh").chmod(0o755)
    print("wrote " + str(len(rows)) + " generated artifact(s); " + str(len(drifted)) + " moved")
    return 0


# FORGE-SCREENING-CARRIER-BEGIN
# GENERATED SECTION. DO NOT HAND-EDIT.
# Generated by seed/forge/screenfreeze.py. Derives the contamination-screening provenance carrier
# from the frozen `screening` block in solution/grounding.yaml and nothing else. It opens no
# connection, reads no wall clock, consults no host language setting, draws no entropy, starts no
# child process, and imports nothing outside this tree.
import hashlib as _forge_hashlib
import json as _forge_json
import pathlib as _forge_pathlib
import sys as _forge_sys

import yaml as _forge_yaml

_FORGE_CARRIER_KEYS = (
    "schema",
    "unit_uuid",
    "screening_roots",
    "authority_mode",
    "source_identifiers",
    "fork_ancestry_snapshot",
    "base_commit_sha",
    "applicable_dates",
    "instrument_versions",
    "atom_result_digests",
    "applicability",
    "sanitization_closure",
    "empty_submission_result",
    "attestations",
    "binding_block",
    "keyid",
    "trust_root_public_key_hex",
    "namespace",
    "normalization_domain_version",
    "signer_identity",
)

_FORGE_BINDING_KEYS = (
    "canonical_bundle_hash",
    "pinned_image_digest",
    "binding_envelope",
)

_FORGE_SCREENING_KEY = "screening"
_FORGE_GROUNDING = "grounding.yaml"
_FORGE_CARRIER = "provenance.yaml"
_FORGE_BANNER = "# GENERATED SECTION. DO NOT HAND-EDIT."


def _forge_here():
    return _forge_pathlib.Path(__file__).resolve().parent


def _forge_sorted(value):
    """Sort every container so two runs over the same frozen bytes emit identical bytes."""
    if isinstance(value, dict):
        return {key: _forge_sorted(value[key]) for key in sorted(value, key=str)}
    if isinstance(value, (list, tuple)):
        return [_forge_sorted(item) for item in value]
    return value


def _forge_frozen_screening():
    """Read the frozen screening block. Absence is refused rather than defaulted."""
    path = _forge_here() / _FORGE_GROUNDING
    with path.open("r", encoding="utf-8") as handle:
        document = _forge_yaml.safe_load(handle)
    block = (document or {}).get(_FORGE_SCREENING_KEY)
    if not isinstance(block, dict):
        raise SystemExit(
            "solution/grounding.yaml carries no frozen `screening` block, so the provenance "
            "carrier cannot be derived. Refusing to emit a carrier over values nobody froze."
        )
    missing = [key for key in _FORGE_CARRIER_KEYS if key not in block]
    unknown = [key for key in sorted(block) if key not in _FORGE_CARRIER_KEYS]
    if missing or unknown:
        raise SystemExit(
            "the frozen `screening` block does not mirror the closed carrier schema: "
            "missing " + repr(missing) + ", unknown " + repr(unknown)
        )
    return block


def _forge_canonical_bytes(payload):
    return _forge_json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")


def _forge_carrier_payload():
    """Assemble the carrier as exactly the closed key set, in the order the schema fixes.

    The binding block is attached AFTER the canonical payload is hashed and never enters the
    preimage, because a payload that contained a hash of itself would have no acyclic ordering.
    """
    block = _forge_frozen_screening()
    payload = {}
    for key in _FORGE_CARRIER_KEYS:
        if key == "binding_block":
            continue
        payload[key] = _forge_sorted(block[key])
    digest = _forge_hashlib.sha256(_forge_canonical_bytes(payload)).hexdigest()

    binding = _forge_sorted(block["binding_block"]) or {}
    shaped = {key: binding.get(key) for key in _FORGE_BINDING_KEYS}
    ordered = {}
    for key in _FORGE_CARRIER_KEYS:
        ordered[key] = shaped if key == "binding_block" else payload[key]
    return ordered, digest


def _forge_carrier_text():
    payload, digest = _forge_carrier_payload()
    header = (
        _FORGE_BANNER + "\n"
        + "# Derived from solution/grounding.yaml `screening` by solution/recompute.py.\n"
        + "# canonical payload sha256 (binding_block excluded from the preimage): " + digest + "\n"
    )
    body = _forge_yaml.safe_dump(
        payload, sort_keys=False, default_flow_style=False, allow_unicode=False, width=100
    )
    return header + body


def _forge_emit_carrier():
    """Write the carrier, or in check mode compare and report drift. Never both."""
    argv = list(_forge_sys.argv[1:])
    check = "--check" in argv
    path = _forge_here() / _FORGE_CARRIER
    text = _forge_carrier_text()
    if check:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
        if current == text:
            return 0
        _forge_sys.stderr.write(
            "drift: " + _FORGE_CARRIER + " does not match the carrier derived from the frozen "
            "`screening` block in " + _FORGE_GROUNDING + "\n"
        )
        return 1
    path.write_text(text, encoding="utf-8")
    return 0


_FORGE_INNER_MAIN = main


def main(*args, **kwargs):
    """Run the host generator, then derive the provenance carrier from the frozen block."""
    status = _FORGE_INNER_MAIN(*args, **kwargs)
    drift = _forge_emit_carrier()
    if drift and not status:
        return drift
    return status

# FORGE-SCREENING-CARRIER-END


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
