# FORGE-CANARY-BEGIN
# 0: 4da619fbbb0605424e46ed1180e5ed4a492e0349588a4efe02f6edbd1ed4f698
# 1: e1992799eb8449cf25569eb40b04c68fbdb19bd210627258cea5a8e317bb6456
# 2: 874ab564947a6bdf11f82e37475841882e1b9ef5e09279de7da4e9b4a4084088
# 3: b2c8f5b5392e8c39ebc7ee72881e5584f96a5cc7e66b6f046eb15134e61f949a
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
