"""GENERATED SECTION. DO NOT HAND-EDIT.

Source: solution/grounding.yaml, generated by solution/recompute.py.

The compiled tests tests/checkers.yaml names in `compiled_test`. Every one of
the ten graded checkers is exercised on BOTH halves here: the clean record it
accepts, and the planted-defect record it refuses with its exact machine-
readable reason. Four further tests replay the stale controls: each named
checker accepts the carried-forward answer under the SUPERSEDED admin-plane
configuration and refuses it under the one in force, which is what makes the
silent mutations in seed/tasks/OER-16/drift.yaml causal rather than asserted.

Self-contained on purpose: the verifier image copies tests/ alone, so no
fixture under solution/ is reachable from here and every record is embedded.
Run it directly:  python3 tests/test_output.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import checkers  # noqa: E402

CONFIG = {
    "_banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
    "_source": "solution/grounding.yaml",
    "anchors": {
        "anchors_state": "absent",
        "baseline_metric": None,
        "gap": "gap-oer-per-family-anchors-unmeasured",
        "target_metric": None
    },
    "claim_tolerance_bpb": 0.01,
    "compute_budget_token_updates": 18000,
    "denominator_frozen_bytes": 6144,
    "evaluation_points": 3,
    "max_vocab_size": 8192,
    "slot": "OER-16",
    "sustain_band_bits_per_byte": 0.03,
    "sustain_points_required": 3
}

SUPERSEDED_CONFIG = {
    "claim_tolerance_bpb": 0.05,
    "compute_budget_token_updates": 24000,
    "denominator_frozen_bytes": 4096,
    "evaluation_points": 3,
    "max_vocab_size": 4096,
    "sustain_band_bits_per_byte": 0.03,
    "sustain_points_required": 2
}

CLEAN = {
    "clean-baseline": {
        "claim": {
            "absence_recorded": True,
            "claimed_bits_per_byte": None,
            "graded_on": "measurement",
            "present": False
        },
        "compute": {
            "budget_token_updates": 18000,
            "counter_source": "harness-counter",
            "spent_token_updates": 18000
        },
        "corpus": {
            "denominator_bytes": 6144,
            "denominator_source": "harness-measured-frozen-eval-corpus",
            "eval_corpus_bytes_measured": 6144
        },
        "frozen_axes": {
            "closing": {
                "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
            },
            "expected": {
                "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
            },
            "opening": {
                "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
            }
        },
        "model_state": {
            "fingerprint_at_measurement": "eaf887a3b44744eaab35ec67950fc4bf59ae3fe2e93767578e407e5ee7acdf52",
            "harness_recomputed_fingerprint": "eaf887a3b44744eaab35ec67950fc4bf59ae3fe2e93767578e407e5ee7acdf52",
            "owner": "verifier-harness",
            "produced_by": "harness-owned-model-state"
        },
        "readout": {
            "graded_bits_per_byte": 3.0339487177141247,
            "pipeline": "raw",
            "raw_bits_per_byte": 3.0339487177141247,
            "smoothing_applied": False
        },
        "schedule": {
            "halted_early": False,
            "point_bits_per_byte": [
                3.0177405369778674,
                3.037730008131508,
                3.051478521676444
            ],
            "points_completed": 3,
            "points_scheduled": 3
        },
        "schema": "oer16.run_record/v1",
        "sequence": {
            "claim_recorded_seq": 1,
            "measurement_computed_seq": 5
        },
        "vocabulary": {
            "loaded_by": "verifier-harness",
            "max_token_bytes": 1,
            "size": 256,
            "source": "submission-tokenizer-json-as-data"
        },
        "vocabulary_refusal": ""
    },
    "clean-reference": {
        "claim": {
            "absence_recorded": False,
            "claimed_bits_per_byte": 1.2532905300907615,
            "graded_on": "measurement",
            "present": True
        },
        "compute": {
            "budget_token_updates": 18000,
            "counter_source": "harness-counter",
            "spent_token_updates": 18000
        },
        "corpus": {
            "denominator_bytes": 6144,
            "denominator_source": "harness-measured-frozen-eval-corpus",
            "eval_corpus_bytes_measured": 6144
        },
        "frozen_axes": {
            "closing": {
                "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
            },
            "expected": {
                "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
            },
            "opening": {
                "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
            }
        },
        "model_state": {
            "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
            "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
            "owner": "verifier-harness",
            "produced_by": "harness-owned-model-state"
        },
        "readout": {
            "graded_bits_per_byte": 1.2532905300907615,
            "pipeline": "raw",
            "raw_bits_per_byte": 1.2532905300907615,
            "smoothing_applied": False
        },
        "schedule": {
            "halted_early": False,
            "point_bits_per_byte": [
                1.2482587441592854,
                1.2638931013359704,
                1.263533159159922
            ],
            "points_completed": 3,
            "points_scheduled": 3
        },
        "schema": "oer16.run_record/v1",
        "sequence": {
            "claim_recorded_seq": 1,
            "measurement_computed_seq": 5
        },
        "vocabulary": {
            "loaded_by": "verifier-harness",
            "max_token_bytes": 16,
            "size": 353,
            "source": "submission-tokenizer-json-as-data"
        },
        "vocabulary_refusal": ""
    }
}

PLANTED = {
    "def-claim-absence-unrecorded": {
        "base": "clean-baseline",
        "fires": "claim_absence_is_recorded",
        "reason": "claim-absence-unrecorded",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": None,
                "graded_on": "measurement",
                "present": False
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "eaf887a3b44744eaab35ec67950fc4bf59ae3fe2e93767578e407e5ee7acdf52",
                "harness_recomputed_fingerprint": "eaf887a3b44744eaab35ec67950fc4bf59ae3fe2e93767578e407e5ee7acdf52",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 3.0339487177141247,
                "pipeline": "raw",
                "raw_bits_per_byte": 3.0339487177141247,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    3.0177405369778674,
                    3.037730008131508,
                    3.051478521676444
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 1,
                "size": 256,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-claim-contradicts-measurement": {
        "base": "clean-reference",
        "fires": "claim_matches_measurement",
        "reason": "claim-contradicts-measurement",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 0.4123,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-claim-recorded-after-measurement": {
        "base": "clean-reference",
        "fires": "claim_sealed_before_measurement",
        "reason": "claim-recorded-after-measurement",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 9,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-compute-budget-overspent": {
        "base": "clean-reference",
        "fires": "compute_budget_respected_as_spent",
        "reason": "compute-budget-overspent",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 36000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-denominator-not-frozen-corpus-bytes": {
        "base": "clean-reference",
        "fires": "denominator_is_frozen_corpus_bytes",
        "reason": "denominator-not-frozen-corpus-bytes",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 9216,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-early-stop-metric-not-established": {
        "base": "clean-reference",
        "fires": "early_stop_establishes_no_metric",
        "reason": "early-stop-metric-not-established",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": True,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 1,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-frozen-axis-mutated": {
        "base": "clean-reference",
        "fires": "frozen_axes_and_vocab_ceiling_hold",
        "reason": "frozen-axis-mutated",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "0000000000000000000000000000000000000000000000000000000000000000",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-graded-figure-not-harness-measured": {
        "base": "clean-reference",
        "fires": "measured_bits_per_byte_is_harness_measured",
        "reason": "graded-figure-not-harness-measured",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "0000000000000000000000000000000000000000000000000000000000000000",
                "owner": "verifier-harness",
                "produced_by": "submission-selected-checkpoint"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-reading-not-sustained": {
        "base": "clean-reference",
        "fires": "reading_sustained_across_scheduled_points",
        "reason": "reading-not-sustained",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2532905300907615,
                    2.1532905300907617,
                    2.353290530090762
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-readout-smoothed": {
        "base": "clean-reference",
        "fires": "graded_readout_is_unsmoothed",
        "reason": "readout-smoothed",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 0.8532905300907615,
                "pipeline": "ema",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": True
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    }
}

STALE = {
    "ctl-budget-verdict-at-superseded-ceiling": {
        "checker": "compute_budget_respected_as_spent",
        "moved_key": "compute_budget_token_updates",
        "reason": "compute-budget-overspent",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 24000,
                "counter_source": "harness-counter",
                "spent_token_updates": 24000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "ctl-denominator-from-superseded-corpus": {
        "checker": "denominator_is_frozen_corpus_bytes",
        "moved_key": "denominator_frozen_bytes",
        "reason": "denominator-not-frozen-corpus-bytes",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 4096,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 4096
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "ctl-divergence-verdict-under-loose-tolerance": {
        "checker": "claim_matches_measurement",
        "moved_key": "claim_tolerance_bpb",
        "reason": "claim-contradicts-measurement",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2832905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2482587441592854,
                    1.2638931013359704,
                    1.263533159159922
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "ctl-sustain-verdict-at-two-points": {
        "checker": "reading_sustained_across_scheduled_points",
        "moved_key": "sustain_points_required",
        "reason": "reading-not-sustained",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 1.2532905300907615,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "expected": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                },
                "opening": {
                    "budget": "2f343eef503377d9b005e19ae19f49981c7c20b329ab6a280e6fca84cd010178",
                    "eval_corpus": "8131123c36c61699b3891c48bf4ebdc3f35d8aa042942894d6e7c4fe478d1d6f",
                    "model": "52fcb8d2dd50351804d73069d30537ae52c148b81269dd1cdf933ebcfdcd917b",
                    "optimizer": "bc3fce797b7435431bc22e132ea16663f503b5727c1d1af40d8840d222b680ec",
                    "train_corpus": "328c896a5bc71f3dd38de313439d34d1633521b7695e3bd42d6cfbc63530fc96"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "harness_recomputed_fingerprint": "6a94cccd5271c27c73acbbb9490ee34aacff1cb419b5ace56a9c17adfe4a735b",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 1.2532905300907615,
                "pipeline": "raw",
                "raw_bits_per_byte": 1.2532905300907615,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    1.2532905300907615,
                    1.2582905300907614,
                    2.1532905300907617
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 16,
                "size": 353,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    }
}


def _verdict(name, record, config):
    return getattr(checkers, name)(record, config)


def _both_halves(name, planted_id):
    for clean_id, clean_record in sorted(CLEAN.items()):
        verdict = _verdict(name, clean_record, CONFIG)
        assert verdict.passed, (name, clean_id, verdict.reason, verdict.detail)
        assert verdict.reason == '', (name, clean_id, verdict.reason)
    row = PLANTED[planted_id]
    verdict = _verdict(name, row['record'], CONFIG)
    assert not verdict.passed, (name, planted_id, 'planted defect was accepted')
    assert verdict.reason == row['reason'], (name, planted_id, verdict.reason)


def _stale_causality(control_id):
    row = STALE[control_id]
    name = row['checker']
    before = _verdict(name, row['record'], SUPERSEDED_CONFIG)
    assert before.passed, (control_id, 'the carried-forward answer already failed',
                           before.reason)
    after = _verdict(name, row['record'], CONFIG)
    assert not after.passed, (control_id, 'the mutation did not move the verdict')
    assert after.reason == row['reason'], (control_id, after.reason)


def test_measured_bits_per_byte_is_harness_measured():
    _both_halves('measured_bits_per_byte_is_harness_measured', 'def-graded-figure-not-harness-measured')


def test_graded_readout_is_unsmoothed():
    _both_halves('graded_readout_is_unsmoothed', 'def-readout-smoothed')


def test_denominator_is_frozen_corpus_bytes():
    _both_halves('denominator_is_frozen_corpus_bytes', 'def-denominator-not-frozen-corpus-bytes')


def test_claim_matches_measurement():
    _both_halves('claim_matches_measurement', 'def-claim-contradicts-measurement')


def test_reading_sustained_across_scheduled_points():
    _both_halves('reading_sustained_across_scheduled_points', 'def-reading-not-sustained')


def test_early_stop_establishes_no_metric():
    _both_halves('early_stop_establishes_no_metric', 'def-early-stop-metric-not-established')


def test_claim_absence_is_recorded():
    _both_halves('claim_absence_is_recorded', 'def-claim-absence-unrecorded')


def test_compute_budget_respected_as_spent():
    _both_halves('compute_budget_respected_as_spent', 'def-compute-budget-overspent')


def test_claim_sealed_before_measurement():
    _both_halves('claim_sealed_before_measurement', 'def-claim-recorded-after-measurement')


def test_frozen_axes_and_vocab_ceiling_hold():
    _both_halves('frozen_axes_and_vocab_ceiling_hold', 'def-frozen-axis-mutated')


def test_ctl_budget_verdict_at_superseded_ceiling():
    _stale_causality('ctl-budget-verdict-at-superseded-ceiling')


def test_ctl_denominator_from_superseded_corpus():
    _stale_causality('ctl-denominator-from-superseded-corpus')


def test_ctl_divergence_verdict_under_loose_tolerance():
    _stale_causality('ctl-divergence-verdict-under-loose-tolerance')


def test_ctl_sustain_verdict_at_two_points():
    _stale_causality('ctl-sustain-verdict-at-two-points')


def main() -> int:
    names = sorted(n for n in globals() if n.startswith('test_'))
    if not names:
        print('no compiled test was collected, which is never a pass')
        return 1
    for name in names:
        globals()[name]()
    print('compiled tests passed: ' + str(len(names)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
