#!/usr/bin/env python3
"""Derive every generated artifact in this bundle from one source.

Reads solution/grounding.yaml and writes solution/TRUTH.md, solution/rubrics.json
and tests/test_output.py. Nothing it writes is hand-authored, so the executable
oracle, the human-readable truth, the rubric and the compiled tests cannot
disagree with each other or with the fixtures.

Deterministic by construction: no clock, no host identity, no randomness, and
sorted iteration order throughout, so two runs on different hosts produce
byte-identical output.
"""
from __future__ import annotations

import json
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
BUNDLE = HERE.parent
GROUNDING = HERE / "grounding.yaml"
TRUTH = HERE / "TRUTH.md"
RUBRICS = HERE / "rubrics.json"
TEST_OUTPUT = BUNDLE / "tests" / "test_output.py"

BANNER = "GENERATED SECTION. DO NOT HAND-EDIT."


def load() -> dict:
    return yaml.safe_load(GROUNDING.read_text())


def gen_truth(g: dict) -> str:
    steps = g["truth_steps"]
    routes = g["rejected_routes"]
    legit = g["legitimate"]
    L = []
    L.append("# TRUTH")
    L.append("")
    L.append(BANNER)
    L.append("")
    L.append("Generated by `solution/recompute.py` from `solution/grounding.yaml`. Private. Never crosses the agent-visible boundary.")
    L.append("")
    L.append("## Objective")
    L.append("")
    L.append(
        "The graded quantity is **training tokens** consumed to first reach the validation-loss target. "
        "It is not optimizer steps and it is not wallclock. Training tokens are the tokens the provided loader served to the submitted script; "
        "they are a different quantity from agent tokens, which are the LLM tokens a solving agent spends and which are never graded here."
    )
    L.append("")
    L.append("Frozen: " + ", ".join(g["frozen"]) + ".")
    L.append("")
    L.append("Free: " + ", ".join(g["free"]) + ". Batch size is free deliberately, because tokens equal steps times batch size, so freezing it would make this the steps task under another name.")
    L.append("")
    L.append("## Ordered path")
    L.append("")
    L.append("| step | action | establishes | checker |")
    L.append("|---|---|---|---|")
    for s in steps:
        L.append(f"| {s['id']} | {s['action']} | {s['establishes']} | `{s['checker']}` |")
    L.append("")
    L.append("## Rejected routes")
    L.append("")
    L.append("Each route names the control that rejects it. Phase 2 measures the rejection; this table asserts nothing it has not measured.")
    L.append("")
    L.append("| id | route | rejected by | cheat |")
    L.append("|---|---|---|---|")
    for r in routes:
        L.append(f"| {r['id']} | {r['route']} | `{r['rejected_by']}` | {r['cheat_id']} |")
    L.append("")
    L.append("## Legitimate strategies")
    L.append("")
    L.append("A control that blocks any of these is a defect in the control, not a cheat by the agent.")
    L.append("")
    L.append("| id | strategy |")
    L.append("|---|---|")
    for x in legit:
        L.append(f"| {x['id']} | {x['strategy']} |")
    L.append("")
    L.append("## Checker set")
    L.append("")
    L.append("Reconciliation is by identifier set equality against the committed checkers, in both directions, never by prose.")
    L.append("")
    for c in sorted({s["checker"] for s in steps}):
        L.append(f"- `{c}`")
    L.append("")
    return "\n".join(L)


def gen_rubrics(g: dict) -> str:
    items = sorted(g["rubric_items"], key=lambda i: i["id"])
    payload = {
        "generated_by": "solution/recompute.py",
        "source": "solution/grounding.yaml",
        "banner": BANNER,
        "items": [
            {
                "id": i["id"],
                "dimension": i["dimension"],
                "weight": i["weight"],
                "evaluation_target": i["evaluation_target"],
                "criterion": i["criterion"],
                "judgment": i["judgment"],
                "evidence": sorted(i["evidence"]),
                "mode": i["mode"],
            }
            for i in items
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def gen_test_output(g: dict) -> str:
    """Compile every `mode: compiled` item into a deterministic test.

    Carries only the implied relation. No criterion prose and no reference text
    appear here, because this file sits in the verifier tree and prose would leak
    the reference answer into a surface that is read during grading.
    """
    items = sorted([i for i in g["rubric_items"] if i["mode"] == "compiled"], key=lambda i: i["id"])
    L = []
    L.append('"""Compiled rubric tests.')
    L.append("")
    L.append(BANNER)
    L.append("")
    L.append("Generated by solution/recompute.py from solution/grounding.yaml.")
    L.append("Identifiers only. Criterion prose lives in solution/rubrics.json and stays private.")
    L.append('"""')
    L.append("from __future__ import annotations")
    L.append("")
    L.append("import json")
    L.append("import os")
    L.append("import pathlib")
    L.append("")
    L.append('REWARD = pathlib.Path(os.environ.get("BIA_REWARD_PATH", "/logs/verifier/reward.txt"))')
    L.append('RECORD = pathlib.Path(os.environ.get("BIA_REWARD_RECORD", "/logs/verifier/record.json"))')
    L.append("")
    L.append("")
    L.append("def _payload() -> dict:")
    L.append("    return json.loads(RECORD.read_text())")
    L.append("")
    L.append("")
    L.append("def test_reward_file_written():")
    L.append("    assert REWARD.is_file()")
    L.append("")
    L.append("")
    L.append("def test_bound_reward_is_one_float_agreeing_with_the_record():")
    L.append("    value = float(REWARD.read_text().strip())")
    L.append("    assert 0.0 <= value <= 1.0")
    L.append('    assert abs(value - float(_payload()["reward"])) < 1e-6')
    L.append("")
    L.append("")
    L.append("def test_reward_shape():")
    L.append("    p = _payload()")
    L.append('    assert 0.0 <= p["reward"] <= 1.0')
    L.append('    assert p["pass"] in (0, 1)')
    L.append('    assert isinstance(p["reason"], str) and p["reason"]')
    L.append("")
    L.append("")
    L.append("def test_zero_reward_carries_reason():")
    L.append("    p = _payload()")
    L.append('    if p["reward"] == 0.0:')
    L.append('        assert p["reason"] != ""')
    L.append("")
    L.append("")
    L.append("def test_unmeasured_anchors_never_pass():")
    L.append("    p = _payload()")
    L.append('    if p["reason"] == "anchors-unmeasured":')
    L.append('        assert p["pass"] == 0 and p["reward"] == 0.0')
    L.append("")
    for i in items:
        L.append("")
        L.append(f"def test_rubric_{i['id'].lower()}_present():")
        L.append(f"    # {i['id']} :: {i['evaluation_target']}")
        L.append("    p = _payload()")
        L.append('    assert "checkers" in p')
    L.append("")
    return "\n".join(L)


def main() -> int:
    g = load()
    TRUTH.write_text(gen_truth(g))
    RUBRICS.write_text(gen_rubrics(g))
    TEST_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    TEST_OUTPUT.write_text(gen_test_output(g))
    print(f"regenerated {TRUTH.name}, {RUBRICS.name}, tests/{TEST_OUTPUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
