# FORGE-CANARY-BEGIN
# 0: 835cf3dcda8b40280b17d7276310c1bd39df611afd43018c75f7833081b40c83
# 1: 95d4cd5f7da85fc10fd9ed190a5d9bbf97a22b58ce7e4cc1c01b9d0e54e0f192
# 2: d83bd6c668b73a9f524f0a9445f46f9d96615fa35ee1bab170dc0b2a3de95640
# 3: a583c55262050457a1ab988914538b9787efb5e509d3b5c9bea47bf36398ab55
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
