"""Compiled deterministic rubric tests.

GENERATED SECTION. DO NOT HAND-EDIT.

Generated by solution/recompute.py from solution/grounding.yaml. One test per
compiled rubric item, each asserting over the verifier outcome map or the verifier
report. No criterion prose and no reference text appears here.
"""

import json
import os
import pathlib


def _outcomes():
    path = os.environ.get("BIA_OUTCOMES", "/logs/verifier/outcomes.json")
    return json.loads(pathlib.Path(path).read_text(encoding="utf-8"))


def _report():
    path = os.environ.get("BIA_REPORT", "/logs/verifier/report.json")
    return json.loads(pathlib.Path(path).read_text(encoding="utf-8"))


def test_divergence_gate_satisfied():
    assert _outcomes()["divergence_bitwise"] is True


def test_declared_outputs_materialized():
    assert _outcomes()["effect_outputs_materialized"] is True


def test_numeric_posture_intact():
    assert _outcomes()["absence_relaxed_precision"] is True


def test_frozen_surface_intact():
    assert _outcomes()["invariant_frozen_surface"] is True


def test_measurement_protocol_ordered():
    assert _outcomes()["ordering_measurement_protocol"] is True


def test_reward_reproducible_from_durations():
    assert _outcomes()["value_reward_recomputed"] is True


def test_reward_within_unit_interval():
    score = _report()["score"]
    assert isinstance(score, float)
    assert 0.0 <= score <= 1.0


def test_zero_score_carries_reason():
    reason = _report()["reason"]
    assert isinstance(reason, str) and reason
