# FORGE-CANARY-BEGIN
# 0: 3030bcc031b0a02c5293754eb1b60b30de0a1f2836fd1e4e4144b659b2c658e5
# 1: 82881f86ebf95aa806e6124b8a6c0053738285b5ebba98d1942c4484996e47bf
# 2: 8295a6e39d7ed5305df19dc99f09554b67d1fb8c952d0fe62706860b3016332a
# 3: 9065e64c840adeb5ddb22acb156dabfd7950864e364b92e0881f316200d84e35
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
