"""GENERATED SECTION. DO NOT HAND-EDIT.

Source: solution/grounding.yaml, generated by solution/recompute.py.

The compiled tests tests/checkers.yaml names in `compiled_test`. Every one of
the ten graded checkers is exercised on BOTH halves here: the clean record it
accepts, and the planted-defect record it refuses with its exact machine-
readable reason. Four further tests replay the stale controls: each named
checker accepts the carried-forward answer under the SUPERSEDED admin-plane
configuration and refuses it under the one in force, which is what makes the
silent mutations in seed/tasks/OER-16/drift.yaml causal rather than asserted.

Self-contained on purpose: the verifier image copies tests/ alone, so no
fixture under solution/ is reachable from here and every record is embedded.
Run it directly:  python3 tests/test_output.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import checkers  # noqa: E402

CONFIG = {
    "_banner": "GENERATED SECTION. DO NOT HAND-EDIT.",
    "_claim_tolerance_note": "Widened from the stand-in's 0.01 because the re-base moved the evaluation split behind the verifier, which makes an exact self-measurement impossible and made a 0.01 band a trap rather than a test. A solver holding out its own slice of the agent-visible corpus can estimate within 0.02, and 0.02 is still tighter than the superseded 0.05, so the stale control ctl-divergence-verdict-under-loose-tolerance keeps its direction: its planted discrepancy of 0.03 passes at 0.05 and fails here.",
    "_compute_budget_note": "Optimizer STEPS of 524288 tokens each, one forward and one backward per step, not tokens consumed. 3250 is the substrate's baseline_steps_to_target, record 36. The checker field name is unchanged so the declared grading surface survives the re-base; the unit it counts is redefined in environment/frozen/optimizer_config.json.",
    "_denominator_note": "The byte length of the verifier's held-out FineWeb slice, pinned by environment/frozen/data_config.json validation.held_out_slice_bytes. The slice is absent from environment/ and from the agent image, so the solver cannot measure this quotient and can only estimate it.",
    "_max_vocab_note": "The frozen embedding width from the substrate, superseding the stand-in's 8192 table ceiling. A vocabulary above it cannot be embedded by the frozen architecture at all.",
    "_source": "solution/grounding.yaml",
    "_substrate": "environment/nanogpt_substrate.json",
    "_sustain_band_note": "Measured, and no longer provisional. See sustain_band_authority.",
    "anchors": {
        "anchors_state": "absent",
        "baseline_metric": None,
        "gap": "gap-oer-per-family-anchors-unmeasured",
        "target_metric": None
    },
    "claim_tolerance_bpb": 0.02,
    "compute_budget_token_updates": 3250,
    "denominator_frozen_bytes": 1048576,
    "evaluation_points": 3,
    "max_vocab_size": 50304,
    "slot": "OER-16",
    "sustain_band_bits_per_byte": 0.1,
    "sustain_points_required": 3
}

SUPERSEDED_CONFIG = {
    "claim_tolerance_bpb": 0.05,
    "compute_budget_token_updates": 18000,
    "denominator_frozen_bytes": 6144,
    "evaluation_points": 3,
    "max_vocab_size": 8192,
    "sustain_band_bits_per_byte": 0.03,
    "sustain_points_required": 2
}

CLEAN = {
    "clean-baseline": {
        "claim": {
            "absence_recorded": True,
            "claimed_bits_per_byte": None,
            "graded_on": "measurement",
            "present": False
        },
        "compute": {
            "budget_token_updates": 3250,
            "counter_source": "harness-counter",
            "spent_token_updates": 3250
        },
        "corpus": {
            "denominator_bytes": 1048576,
            "denominator_source": "harness-measured-frozen-eval-corpus",
            "eval_corpus_bytes_measured": 1048576
        },
        "frozen_axes": {
            "closing": {
                "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
            },
            "expected": {
                "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
            },
            "opening": {
                "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
            }
        },
        "model_state": {
            "fingerprint_at_measurement": "78744ee60b4f0219f834ccf02076e1b9216bb3ae46dc54ed4f505dd2de2483e1",
            "harness_recomputed_fingerprint": "78744ee60b4f0219f834ccf02076e1b9216bb3ae46dc54ed4f505dd2de2483e1",
            "owner": "verifier-harness",
            "produced_by": "harness-owned-model-state"
        },
        "readout": {
            "graded_bits_per_byte": 4.534020213761907,
            "pipeline": "raw",
            "raw_bits_per_byte": 4.534020213761907,
            "smoothing_applied": False
        },
        "schedule": {
            "halted_early": False,
            "point_bits_per_byte": [
                4.48987489280909,
                4.512570804278594,
                4.5996357181940475
            ],
            "points_completed": 3,
            "points_scheduled": 3
        },
        "schema": "oer16.run_record/v1",
        "sequence": {
            "claim_recorded_seq": 1,
            "measurement_computed_seq": 5
        },
        "vocabulary": {
            "loaded_by": "verifier-harness",
            "max_token_bytes": 1,
            "size": 256,
            "source": "submission-tokenizer-json-as-data"
        },
        "vocabulary_refusal": ""
    },
    "clean-reference": {
        "claim": {
            "absence_recorded": False,
            "claimed_bits_per_byte": 4.073010147421838,
            "graded_on": "measurement",
            "present": True
        },
        "compute": {
            "budget_token_updates": 3250,
            "counter_source": "harness-counter",
            "spent_token_updates": 3250
        },
        "corpus": {
            "denominator_bytes": 1048576,
            "denominator_source": "harness-measured-frozen-eval-corpus",
            "eval_corpus_bytes_measured": 1048576
        },
        "frozen_axes": {
            "closing": {
                "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
            },
            "expected": {
                "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
            },
            "opening": {
                "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
            }
        },
        "model_state": {
            "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
            "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
            "owner": "verifier-harness",
            "produced_by": "harness-owned-model-state"
        },
        "readout": {
            "graded_bits_per_byte": 4.073010147421838,
            "pipeline": "raw",
            "raw_bits_per_byte": 4.073010147421838,
            "smoothing_applied": False
        },
        "schedule": {
            "halted_early": False,
            "point_bits_per_byte": [
                4.016595743152471,
                4.061015889109548,
                4.141473813147759
            ],
            "points_completed": 3,
            "points_scheduled": 3
        },
        "schema": "oer16.run_record/v1",
        "sequence": {
            "claim_recorded_seq": 1,
            "measurement_computed_seq": 5
        },
        "vocabulary": {
            "loaded_by": "verifier-harness",
            "max_token_bytes": 9,
            "size": 768,
            "source": "submission-tokenizer-json-as-data"
        },
        "vocabulary_refusal": ""
    }
}

PLANTED = {
    "def-claim-absence-unrecorded": {
        "base": "clean-baseline",
        "fires": "claim_absence_is_recorded",
        "reason": "claim-absence-unrecorded",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": None,
                "graded_on": "measurement",
                "present": False
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "78744ee60b4f0219f834ccf02076e1b9216bb3ae46dc54ed4f505dd2de2483e1",
                "harness_recomputed_fingerprint": "78744ee60b4f0219f834ccf02076e1b9216bb3ae46dc54ed4f505dd2de2483e1",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.534020213761907,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.534020213761907,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.48987489280909,
                    4.512570804278594,
                    4.5996357181940475
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 1,
                "size": 256,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-claim-contradicts-measurement": {
        "base": "clean-reference",
        "fires": "claim_matches_measurement",
        "reason": "claim-contradicts-measurement",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 0.4123,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-claim-recorded-after-measurement": {
        "base": "clean-reference",
        "fires": "claim_sealed_before_measurement",
        "reason": "claim-recorded-after-measurement",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 9,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-compute-budget-overspent": {
        "base": "clean-reference",
        "fires": "compute_budget_respected_as_spent",
        "reason": "compute-budget-overspent",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 6500
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-denominator-not-frozen-corpus-bytes": {
        "base": "clean-reference",
        "fires": "denominator_is_frozen_corpus_bytes",
        "reason": "denominator-not-frozen-corpus-bytes",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1655197,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-early-stop-metric-not-established": {
        "base": "clean-reference",
        "fires": "early_stop_establishes_no_metric",
        "reason": "early-stop-metric-not-established",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": True,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 1,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-frozen-axis-mutated": {
        "base": "clean-reference",
        "fires": "frozen_axes_and_vocab_ceiling_hold",
        "reason": "frozen-axis-mutated",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "0000000000000000000000000000000000000000000000000000000000000000",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-graded-figure-not-harness-measured": {
        "base": "clean-reference",
        "fires": "measured_bits_per_byte_is_harness_measured",
        "reason": "graded-figure-not-harness-measured",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "0000000000000000000000000000000000000000000000000000000000000000",
                "owner": "verifier-harness",
                "produced_by": "submission-selected-checkpoint"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-reading-not-sustained": {
        "base": "clean-reference",
        "fires": "reading_sustained_across_scheduled_points",
        "reason": "reading-not-sustained",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.073010147421838,
                    4.973010147421839,
                    5.173010147421838
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "def-readout-smoothed": {
        "base": "clean-reference",
        "fires": "graded_readout_is_unsmoothed",
        "reason": "readout-smoothed",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 3.6730101474218384,
                "pipeline": "ema",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": True
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    }
}

STALE = {
    "ctl-budget-verdict-at-superseded-ceiling": {
        "checker": "compute_budget_respected_as_spent",
        "moved_key": "compute_budget_token_updates",
        "reason": "compute-budget-overspent",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 18000,
                "counter_source": "harness-counter",
                "spent_token_updates": 18000
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "ctl-denominator-from-superseded-corpus": {
        "checker": "denominator_is_frozen_corpus_bytes",
        "moved_key": "denominator_frozen_bytes",
        "reason": "denominator-not-frozen-corpus-bytes",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 6144,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 6144
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "ctl-divergence-verdict-under-loose-tolerance": {
        "checker": "claim_matches_measurement",
        "moved_key": "claim_tolerance_bpb",
        "reason": "claim-contradicts-measurement",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.103010147421839,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.016595743152471,
                    4.061015889109548,
                    4.141473813147759
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    },
    "ctl-sustain-verdict-at-two-points": {
        "checker": "reading_sustained_across_scheduled_points",
        "moved_key": "sustain_points_required",
        "reason": "reading-not-sustained",
        "record": {
            "claim": {
                "absence_recorded": False,
                "claimed_bits_per_byte": 4.073010147421838,
                "graded_on": "measurement",
                "present": True
            },
            "compute": {
                "budget_token_updates": 3250,
                "counter_source": "harness-counter",
                "spent_token_updates": 3250
            },
            "corpus": {
                "denominator_bytes": 1048576,
                "denominator_source": "harness-measured-frozen-eval-corpus",
                "eval_corpus_bytes_measured": 1048576
            },
            "frozen_axes": {
                "closing": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "expected": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                },
                "opening": {
                    "architecture": "1f4b0820a969d8ce4a4996ec997789865eb4139f14d362d18f1928c40a758725",
                    "budget": "ac0b6349bba573634c392c9d9f0588e6a0ffb94a51d0a2f1d43fd05b5898d6b9",
                    "data": "fb18ecf68982f46551d4b5f7ccef1b9c6a091f369f70cbde0f02854c1abcf689",
                    "model": "6d01c12f6929db8609ed14951296267ed58958a38215de6bcc8dfdb6aa6eb0d3",
                    "optimizer": "0439f2df7429ab8a55cf76a4e77435ff01ddf807ff97aeb5ac9900b468718408",
                    "substrate": "cc5d77abb0adb8345337ba4918a549057cb0c1fa1fe60292d165c1274b97ec7e"
                }
            },
            "model_state": {
                "fingerprint_at_measurement": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "harness_recomputed_fingerprint": "37950e8ebe65df0613da2f7af1df72c200c08dd4bbc74b32076dac3fb5b8163e",
                "owner": "verifier-harness",
                "produced_by": "harness-owned-model-state"
            },
            "readout": {
                "graded_bits_per_byte": 4.073010147421838,
                "pipeline": "raw",
                "raw_bits_per_byte": 4.073010147421838,
                "smoothing_applied": False
            },
            "schedule": {
                "halted_early": False,
                "point_bits_per_byte": [
                    4.073010147421838,
                    4.078010147421838,
                    4.973010147421839
                ],
                "points_completed": 3,
                "points_scheduled": 3
            },
            "schema": "oer16.run_record/v1",
            "sequence": {
                "claim_recorded_seq": 1,
                "measurement_computed_seq": 5
            },
            "vocabulary": {
                "loaded_by": "verifier-harness",
                "max_token_bytes": 9,
                "size": 768,
                "source": "submission-tokenizer-json-as-data"
            },
            "vocabulary_refusal": ""
        }
    }
}


def _verdict(name, record, config):
    return getattr(checkers, name)(record, config)


def _both_halves(name, planted_id):
    for clean_id, clean_record in sorted(CLEAN.items()):
        verdict = _verdict(name, clean_record, CONFIG)
        assert verdict.passed, (name, clean_id, verdict.reason, verdict.detail)
        assert verdict.reason == '', (name, clean_id, verdict.reason)
    row = PLANTED[planted_id]
    verdict = _verdict(name, row['record'], CONFIG)
    assert not verdict.passed, (name, planted_id, 'planted defect was accepted')
    assert verdict.reason == row['reason'], (name, planted_id, verdict.reason)


def _stale_causality(control_id):
    row = STALE[control_id]
    name = row['checker']
    before = _verdict(name, row['record'], SUPERSEDED_CONFIG)
    assert before.passed, (control_id, 'the carried-forward answer already failed',
                           before.reason)
    after = _verdict(name, row['record'], CONFIG)
    assert not after.passed, (control_id, 'the mutation did not move the verdict')
    assert after.reason == row['reason'], (control_id, after.reason)


def test_measured_bits_per_byte_is_harness_measured():
    _both_halves('measured_bits_per_byte_is_harness_measured', 'def-graded-figure-not-harness-measured')


def test_graded_readout_is_unsmoothed():
    _both_halves('graded_readout_is_unsmoothed', 'def-readout-smoothed')


def test_denominator_is_frozen_corpus_bytes():
    _both_halves('denominator_is_frozen_corpus_bytes', 'def-denominator-not-frozen-corpus-bytes')


def test_claim_matches_measurement():
    _both_halves('claim_matches_measurement', 'def-claim-contradicts-measurement')


def test_reading_sustained_across_scheduled_points():
    _both_halves('reading_sustained_across_scheduled_points', 'def-reading-not-sustained')


def test_early_stop_establishes_no_metric():
    _both_halves('early_stop_establishes_no_metric', 'def-early-stop-metric-not-established')


def test_claim_absence_is_recorded():
    _both_halves('claim_absence_is_recorded', 'def-claim-absence-unrecorded')


def test_compute_budget_respected_as_spent():
    _both_halves('compute_budget_respected_as_spent', 'def-compute-budget-overspent')


def test_claim_sealed_before_measurement():
    _both_halves('claim_sealed_before_measurement', 'def-claim-recorded-after-measurement')


def test_frozen_axes_and_vocab_ceiling_hold():
    _both_halves('frozen_axes_and_vocab_ceiling_hold', 'def-frozen-axis-mutated')


def test_ctl_budget_verdict_at_superseded_ceiling():
    _stale_causality('ctl-budget-verdict-at-superseded-ceiling')


def test_ctl_denominator_from_superseded_corpus():
    _stale_causality('ctl-denominator-from-superseded-corpus')


def test_ctl_divergence_verdict_under_loose_tolerance():
    _stale_causality('ctl-divergence-verdict-under-loose-tolerance')


def test_ctl_sustain_verdict_at_two_points():
    _stale_causality('ctl-sustain-verdict-at-two-points')


def main() -> int:
    names = sorted(n for n in globals() if n.startswith('test_'))
    if not names:
        print('no compiled test was collected, which is never a pass')
        return 1
    for name in names:
        globals()[name]()
    print('compiled tests passed: ' + str(len(names)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
