# FORGE-CANARY-BEGIN
# 0: be73fed7536aafa99eebf6db75eb68d65afba5c174f42bccc078d5d2bbd4d38b
# 1: 8827333c6b85938ca32144adcba4c3d1ade81b0395aa324493a99b0f05ce9ebf
# 2: 0bf2a3bae0eed05bd7aa5afd6393ee48127584226c00365afb45c5373329a3c2
# 3: b11a38d622533fd89f9ed392a450392e4161e4c6176e73e4846c5e74a5066d63
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml, generated by solution/recompute.py.
#
# The oracle entry point. It installs the reference solution at the bound
# submission path and exercises it once against the frozen half, so the
# artifacts the verifier reads as data exist before grading starts.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bundle="$(cd "${here}/.." && pwd)"
frozen="${OER16_FROZEN_DIR:-${bundle}/environment/frozen}"
submission="${OER16_SUBMISSION:-/app/submission.py}"
workdir="${OER16_SOLVE_OUT:-${TMPDIR:-/tmp}/oer16-solve}"

mkdir -p "$(dirname "${submission}")" "${workdir}"
cp "${here}/reference.py" "${submission}"

# Run it exactly as the verifier runs a submission: alone, isolated
# interpreter, two positional arguments, artifacts written as data.
python3 -I -S "${submission}" "${frozen}" "${workdir}"

echo "installed ${submission}; artifacts in ${workdir}"
