# FORGE-CANARY-BEGIN
# 0: d3e56e2cd793eabe32f87dbc8ab639a2b61dcda813e5ef828a08650dfb141c0e
# 1: 1a448a95ce4cd6a9c4336b7488cef94f7914d560e0c89a9c104098de53f77439
# 2: 9768a7d0d02ded08575cd795ae7b34d71a322b663fb24178d0d2c57748fb5aa4
# 3: 87679370ff086981b41c73c5553f330f73b2a660fe343fb69d27243b8b078a58
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
