# FORGE-CANARY-BEGIN
# 0: 2bea54b6c6108690a92d784c1d99f03d43579183c01317190d725922da35f174
# 1: 7f1600eb9f7d08f4317dd29f2bbeedc36b9b95b9aa163fa13927bc2826181f2a
# 2: eb63e63d7a504dca7b120a3b2c90fe371ff5fe5592f2e9cfb8bab2c55bda6f6b
# 3: 7f548c41cfef32f8196f47bab7bd6866c9a9c38fa0a204612cbda4a2a4c5976e
# FORGE-CANARY-END
#!/usr/bin/env bash
# GENERATED SECTION. DO NOT HAND-EDIT.
# Source: solution/grounding.yaml. Generated by solution/recompute.py.
#
# The solver entry point. It places the reference search where the verifier's runner
# picks it up. The reference never writes a reward and never reports a figure of its
# own; the harness measures, the verifier recomputes.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUBMISSION_DIR="${OER23_SUBMISSION_DIR:-/workspace/submission}"

mkdir -p "${SUBMISSION_DIR}"
cp "${HERE}/reference.py" "${SUBMISSION_DIR}/search.py"
echo "OER-23 reference search placed at ${SUBMISSION_DIR}/search.py"
